const players = [

{
    id: 1,
    name: "Viv Richards",
    type: "Middle Order Batter",
    othertype: "Part Time Off Spinner",
    handtype: "Right Hand Batter",
    country: "westindies",
    matches: 187,
    totalRuns: 6721,
    highestScore: 189,
    catches: 101,
    fours: 620,
    sixes: 50,
    fifties: 45,
    hundreds: 11,
    wickets: 118,
    economy: 4.4,
    battingAverage: 47,
    battingStrikeRate: 90,
    highestBowlingSpeed: "130 km/h"
},
 
{
    id: 2,
    name: "Desmond Haynes",
    type: "Opening Batter",
    othertype: "Right Hand Batter",
    handtype: "Right Hand Batter",
    country: "westindies",
    matches: 238,
    totalRuns: 8648,
    highestScore: 152,
    catches: 59,
    fours: 800,
    sixes: 24,
    fifties: 57,
    hundreds: 17,
    wickets: 1,
    economy: 5,
    battingAverage: 41,
    battingStrikeRate: 63,
    highestBowlingSpeed: "110 km/h"
},
 
{
    id: 3,
    name: "Kapil Dev",
    type: "Fast Bowling All-Rounder",
    othertype: "captain",
    handtype: "Right Hand Batter / Right Arm Fast",
    country: "india",
    matches: 225,
    totalRuns: 3783,
    highestScore: 175,
    catches: 71,
    fours: 290,
    sixes: 67,
    fifties: 14,
    hundreds: 1,
    wickets: 253,
    economy: 3.7,
    battingAverage: 23,
    battingStrikeRate: 95,
    highestBowlingSpeed: "140 km/h"
},
 
{
    id: 4,
    name: "Imran Khan",
    type: "Fast Bowling All-Rounder",
    othertype: "captain",
    handtype: "Right Hand Batter / Right Arm Fast",
    country: "pakistan",
    matches: 175,
    totalRuns: 3709,
    highestScore: 102,
    catches: 36,
    fours: 270,
    sixes: 25,
    fifties: 19,
    hundreds: 1,
    wickets: 182,
    economy: 3.9,
    battingAverage: 33,
    battingStrikeRate: 72,
    highestBowlingSpeed: "140 km/h"
},
 
{
    id: 5,
    name: "Richard Hadlee",
    type: "Fast Bowling All-Rounder",
    othertype: "Lower Order Batter",
    handtype: "Right Hand Batter / Right Arm Fast",
    country: "newzealand",
    matches: 115,
    totalRuns: 1751,
    highestScore: 79,
    catches: 27,
    fours: 130,
    sixes: 20,
    fifties: 4,
    hundreds: 0,
    wickets: 158,
    economy: 3.3,
    battingAverage: 21,
    battingStrikeRate: 75,
    highestBowlingSpeed: "142 km/h"
},
 
{
    id: 6,
    name: "Mohammad Azharuddin",
    type: "Middle Order Batter",
    othertype: "Part Time Off Spinner",
    handtype: "Right Hand Batter",
    country: "india",
    matches: 334,
    totalRuns: 9378,
    highestScore: 153,
    catches: 156,
    fours: 810,
    sixes: 45,
    fifties: 58,
    hundreds: 7,
    wickets: 12,
    economy: 5.5,
    battingAverage: 36,
    battingStrikeRate: 74,
    highestBowlingSpeed: "122 km/h"
},
 
{
    id: 7,
    name: "Allan Donald",
    type: "Fast Bowler",
    othertype: "Tailender",
    handtype: "Right Hand Batter / Right Arm Fast",
    country: "southafrica",
    matches: 164,
    totalRuns: 95,
    highestScore: 19,
    catches: 17,
    fours: 8,
    sixes: 1,
    fifties: 0,
    hundreds: 0,
    wickets: 272,
    economy: 4.1,
    battingAverage: 6,
    battingStrikeRate: 55,
    highestBowlingSpeed: "148 km/h"
},
 
{
    id: 8,
    name: "Wasim Akram",
    type: "Fast Bowling All-Rounder",
    othertype: "Lower Order Batter",
    handtype: "Left Hand Batter / Left Arm Fast",
    country: "pakistan",
    matches: 356,
    totalRuns: 3717,
    highestScore: 86,
    catches: 88,
    fours: 300,
    sixes: 90,
    fifties: 6,
    hundreds: 0,
    wickets: 502,
    economy: 3.9,
    battingAverage: 16,
    battingStrikeRate: 88,
    highestBowlingSpeed: "150 km/h"
},
 
{
    id: 9,
    name: "Courtney Walsh",
    type: "Fast Bowler",
    othertype: "Tailender",
    handtype: "Right Hand Batter / Right Arm Fast",
    country: "westindies",
    matches: 205,
    totalRuns: 321,
    highestScore: 30,
    catches: 27,
    fours: 25,
    sixes: 4,
    fifties: 0,
    hundreds: 0,
    wickets: 227,
    economy: 3.8,
    battingAverage: 7,
    battingStrikeRate: 52,
    highestBowlingSpeed: "145 km/h"
},
 
{
    id: 10,
    name: "Curtly Ambrose",
    type: "Fast Bowler",
    othertype: "Tailender",
    handtype: "Left Hand Batter / Right Arm Fast",
    country: "westindies",
    matches: 176,
    totalRuns: 639,
    highestScore: 31,
    catches: 45,
    fours: 40,
    sixes: 5,
    fifties: 0,
    hundreds: 0,
    wickets: 225,
    economy: 3.5,
    battingAverage: 11,
    battingStrikeRate: 56,
    highestBowlingSpeed: "146 km/h"
},
 
{
    id: 11,
    name: "Saeed Anwar",
    type: "Opening Batter",
    othertype: "Left Hand Batter",
    handtype: "Left Hand Batter",
    country: "pakistan",
    matches: 247,
    totalRuns: 8824,
    highestScore: 194,
    catches: 49,
    fours: 900,
    sixes: 89,
    fifties: 43,
    hundreds: 20,
    wickets: 6,
    economy: 5,
    battingAverage: 39,
    battingStrikeRate: 80,
    highestBowlingSpeed: "110 km/h"
},
 
{
    id: 12,
    name: "Brian Lara",
    type: "Top Order Batter",
    othertype: "Middle Order Batter",
    handtype: "Left Hand Batter",
    country: "westindies",
    matches: 299,
    totalRuns: 10405,
    highestScore: 169,
    catches: 120,
    fours: 960,
    sixes: 133,
    fifties: 63,
    hundreds: 19,
    wickets: 4,
    economy: 4.9,
    battingAverage: 40,
    battingStrikeRate: 79,
    highestBowlingSpeed: "118 km/h"
},
 
{
    id: 13,
    name: "Sachin Tendulkar",
    type: "Batting All-Rounder",
    othertype: "Top Order Batter",
    handtype: "Right Hand Batter",
    country: "india",
    matches: 463,
    totalRuns: 18426,
    highestScore: 200,
    catches: 140,
    fours: 2016,
    sixes: 195,
    fifties: 96,
    hundreds: 49,
    wickets: 154,
    economy: 5.1,
    battingAverage: 44,
    battingStrikeRate: 86,
    highestBowlingSpeed: "134 km/h"
},
 
{
    id: 14,
    name: "Javagal Srinath",
    type: "Fast Bowler",
    othertype: "Lower Order Batter",
    handtype: "Right Hand Batter / Right Arm Fast",
    country: "india",
    matches: 229,
    totalRuns: 883,
    highestScore: 53,
    catches: 32,
    fours: 70,
    sixes: 12,
    fifties: 1,
    hundreds: 0,
    wickets: 315,
    economy: 4.4,
    battingAverage: 11,
    battingStrikeRate: 70,
    highestBowlingSpeed: "149 km/h"
},
 
{
    id: 15,
    name: "Shane Warne",
    type: "Leg Spinner",
    othertype: "Lower Order Batter",
    handtype: "Right Hand Batter / Right Arm Leg Spin",
    country: "australia",
    matches: 194,
    totalRuns: 1018,
    highestScore: 55,
    catches: 80,
    fours: 80,
    sixes: 10,
    fifties: 1,
    hundreds: 0,
    wickets: 293,
    economy: 4.3,
    battingAverage: 13,
    battingStrikeRate: 72,
    highestBowlingSpeed: "128 km/h"
},
 
{
    id: 16,
    name: "Inzamam-ul-Haq",
    type: "Middle Order Batter",
    othertype: "captain",
    handtype: "Right Hand Batter",
    country: "pakistan",
    matches: 378,
    totalRuns: 11739,
    highestScore: 137,
    catches: 113,
    fours: 1000,
    sixes: 144,
    fifties: 83,
    hundreds: 10,
    wickets: 3,
    economy: 5.6,
    battingAverage: 39,
    battingStrikeRate: 74,
    highestBowlingSpeed: "116 km/h"
},
 
{
    id: 17,
    name: "Anil Kumble",
    type: "Leg Spinner",
    othertype: "Lower Order Batter",
    handtype: "Right Hand Batter / Right Arm Leg Spin",
    country: "india",
    matches: 271,
    totalRuns: 938,
    highestScore: 26,
    catches: 85,
    fours: 60,
    sixes: 5,
    fifties: 0,
    hundreds: 0,
    wickets: 337,
    economy: 4.3,
    battingAverage: 11,
    battingStrikeRate: 66,
    highestBowlingSpeed: "126 km/h"
},
 
{
    id: 18,
    name: "Waqar Younis",
    type: "Fast Bowler",
    othertype: "Tailender",
    handtype: "Right Hand Batter / Right Arm Fast",
    country: "pakistan",
    matches: 262,
    totalRuns: 969,
    highestScore: 37,
    catches: 32,
    fours: 80,
    sixes: 12,
    fifties: 0,
    hundreds: 0,
    wickets: 416,
    economy: 4.7,
    battingAverage: 11,
    battingStrikeRate: 68,
    highestBowlingSpeed: "153 km/h"
},
 
{
    id: 19,
    name: "Aravinda de Silva",
    type: "Batting All-Rounder",
    othertype: "Middle Order Batter",
    handtype: "Right Hand Batter",
    country: "srilanka",
    matches: 308,
    totalRuns: 9284,
    highestScore: 145,
    catches: 95,
    fours: 830,
    sixes: 60,
    fifties: 64,
    hundreds: 11,
    wickets: 106,
    economy: 4.7,
    battingAverage: 34,
    battingStrikeRate: 81,
    highestBowlingSpeed: "124 km/h"
},
 
{
    id: 20,
    name: "Saqlain Mushtaq",
    type: "Off Spinner",
    othertype: "Lower Order Batter",
    handtype: "Right Hand Batter / Right Arm Off Spin",
    country: "pakistan",
    matches: 169,
    totalRuns: 711,
    highestScore: 37,
    catches: 35,
    fours: 50,
    sixes: 8,
    fifties: 0,
    hundreds: 0,
    wickets: 288,
    economy: 4.3,
    battingAverage: 10,
    battingStrikeRate: 58,
    highestBowlingSpeed: "118 km/h"
},
 
{
    id: 21,
    name: "Steve Waugh",
    type: "All-Rounder",
    othertype: "Middle Order Batter",
    handtype: "Right Hand Batter / Right Arm Medium",
    country: "australia",
    matches: 325,
    totalRuns: 7569,
    highestScore: 120,
    catches: 111,
    fours: 620,
    sixes: 50,
    fifties: 45,
    hundreds: 3,
    wickets: 195,
    economy: 4.6,
    battingAverage: 32,
    battingStrikeRate: 76,
    highestBowlingSpeed: "128 km/h"
},
 
{
    id: 22,
    name: "Grant Flower",
    type: "Opening Batter",
    othertype: "Part Time Spinner",
    handtype: "Left Hand Batter",
    country: "zimbabwe",
    matches: 221,
    totalRuns: 6571,
    highestScore: 142,
    catches: 86,
    fours: 580,
    sixes: 40,
    fifties: 40,
    hundreds: 6,
    wickets: 104,
    economy: 4.7,
    battingAverage: 33,
    battingStrikeRate: 72,
    highestBowlingSpeed: "112 km/h"
},
 
{
    id: 23,
    name: "Adam Gilchrist",
    type: "Wicket-Keeper Batter",
    othertype: "captain",
    handtype: "Left Hand Batter",
    country: "australia",
    matches: 287,
    totalRuns: 9619,
    highestScore: 172,
    catches: 417,
    fours: 1180,
    sixes: 149,
    fifties: 55,
    hundreds: 16,
    wickets: 0,
    economy: 0,
    battingAverage: 35,
    battingStrikeRate: 96,
    highestBowlingSpeed: "0 km/h"
},
 
{
    id: 24,
    name: "Glenn McGrath",
    type: "Fast Bowler",
    othertype: "Tailender",
    handtype: "Left Hand Batter / Right Arm Fast",
    country: "australia",
    matches: 250,
    totalRuns: 115,
    highestScore: 11,
    catches: 37,
    fours: 8,
    sixes: 0,
    fifties: 0,
    hundreds: 0,
    wickets: 381,
    economy: 3.9,
    battingAverage: 4,
    battingStrikeRate: 40,
    highestBowlingSpeed: "145 km/h"
},
 
{
    id: 25,
    name: "Chaminda Vaas",
    type: "Fast Bowler",
    othertype: "Lower Order Batter",
    handtype: "Left Hand Batter / Left Arm Fast",
    country: "srilanka",
    matches: 322,
    totalRuns: 2025,
    highestScore: 50,
    catches: 60,
    fours: 150,
    sixes: 20,
    fifties: 1,
    hundreds: 0,
    wickets: 400,
    economy: 4.2,
    battingAverage: 15,
    battingStrikeRate: 67,
    highestBowlingSpeed: "140 km/h"
},
 
{
    id: 26,
    name: "Sanath Jayasuriya",
    type: "Batting All-Rounder",
    othertype: "Opening Batter",
    handtype: "Left Hand Batter / Left Arm Spin",
    country: "srilanka",
    matches: 445,
    totalRuns: 13430,
    highestScore: 189,
    catches: 123,
    fours: 1500,
    sixes: 270,
    fifties: 68,
    hundreds: 28,
    wickets: 323,
    economy: 4.8,
    battingAverage: 32,
    battingStrikeRate: 91,
    highestBowlingSpeed: "132 km/h"
},
 
{
    id: 27,
    name: "Michael Bevan",
    type: "Middle Order Batter",
    othertype: "Finisher",
    handtype: "Left Hand Batter",
    country: "australia",
    matches: 232,
    totalRuns: 6912,
    highestScore: 108,
    catches: 69,
    fours: 560,
    sixes: 21,
    fifties: 46,
    hundreds: 6,
    wickets: 36,
    economy: 4.7,
    battingAverage: 53,
    battingStrikeRate: 74,
    highestBowlingSpeed: "118 km/h"
},
 
{
    id: 28,
    name: "Sourav Ganguly",
    type: "Opening Batter",
    othertype: "captain",
    handtype: "Left Hand Batter",
    country: "india",
    matches: 311,
    totalRuns: 11363,
    highestScore: 183,
    catches: 100,
    fours: 1120,
    sixes: 190,
    fifties: 72,
    hundreds: 22,
    wickets: 100,
    economy: 5.1,
    battingAverage: 41,
    battingStrikeRate: 73,
    highestBowlingSpeed: "126 km/h"
},
 
{
    id: 29,
    name: "Muttiah Muralitharan",
    type: "Off Spinner",
    othertype: "Tailender",
    handtype: "Right Hand Batter / Right Arm Off Spin",
    country: "srilanka",
    matches: 350,
    totalRuns: 674,
    highestScore: 33,
    catches: 130,
    fours: 40,
    sixes: 8,
    fifties: 0,
    hundreds: 0,
    wickets: 534,
    economy: 3.9,
    battingAverage: 11,
    battingStrikeRate: 62,
    highestBowlingSpeed: "116 km/h"
},
 
{
    id: 30,
    name: "Paul Collingwood",
    type: "All-Rounder",
    othertype: "Middle Order Batter",
    handtype: "Right Hand Batter / Right Arm Medium",
    country: "england",
    matches: 197,
    totalRuns: 5092,
    highestScore: 120,
    catches: 108,
    fours: 420,
    sixes: 50,
    fifties: 26,
    hundreds: 5,
    wickets: 111,
    economy: 4.9,
    battingAverage: 36,
    battingStrikeRate: 79,
    highestBowlingSpeed: "124 km/h"
},
 
{
    id: 31,
    name: "Ricky Ponting",
    type: "Top Order Batter",
    othertype: "captain",
    handtype: "Right Hand Batter",
    country: "australia",
    matches: 375,
    totalRuns: 13704,
    highestScore: 164,
    catches: 160,
    fours: 1230,
    sixes: 162,
    fifties: 82,
    hundreds: 30,
    wickets: 3,
    economy: 5.2,
    battingAverage: 42,
    battingStrikeRate: 80,
    highestBowlingSpeed: "118 km/h"
},
 
{
    id: 32,
    name: "Chris Cairns",
    type: "All-Rounder",
    othertype: "Middle Order Batter",
    handtype: "Right Hand Batter / Right Arm Fast",
    country: "newzealand",
    matches: 215,
    totalRuns: 4950,
    highestScore: 115,
    catches: 66,
    fours: 380,
    sixes: 153,
    fifties: 26,
    hundreds: 4,
    wickets: 201,
    economy: 4.7,
    battingAverage: 29,
    battingStrikeRate: 84,
    highestBowlingSpeed: "143 km/h"
},
 
{
    id: 33,
    name: "Harbhajan Singh",
    type: "Off Spinner",
    othertype: "Lower Order Batter",
    handtype: "Right Hand Batter / Right Arm Off Spin",
    country: "india",
    matches: 236,
    totalRuns: 1237,
    highestScore: 49,
    catches: 71,
    fours: 90,
    sixes: 25,
    fifties: 0,
    hundreds: 0,
    wickets: 269,
    economy: 4.3,
    battingAverage: 13,
    battingStrikeRate: 74,
    highestBowlingSpeed: "122 km/h"
},
 
{
    id: 34,
    name: "Rahul Dravid",
    type: "Top Order Batter",
    othertype: "captain",
    handtype: "Right Hand Batter",
    country: "india",
    matches: 344,
    totalRuns: 10889,
    highestScore: 153,
    catches: 196,
    fours: 950,
    sixes: 42,
    fifties: 83,
    hundreds: 12,
    wickets: 4,
    economy: 5.4,
    battingAverage: 39,
    battingStrikeRate: 71,
    highestBowlingSpeed: "110 km/h"
},
 
{
    id: 35,
    name: "Shahid Afridi",
    type: "All-Rounder",
    othertype: "captain",
    handtype: "Right Hand Batter / Right Arm Leg Spin",
    country: "pakistan",
    matches: 398,
    totalRuns: 8064,
    highestScore: 124,
    catches: 127,
    fours: 720,
    sixes: 351,
    fifties: 39,
    hundreds: 6,
    wickets: 395,
    economy: 4.6,
    battingAverage: 23,
    battingStrikeRate: 117,
    highestBowlingSpeed: "134 km/h"
},
 
{
    id: 36,
    name: "Herschelle Gibbs",
    type: "Opening Batter",
    othertype: "Part Time Bowler",
    handtype: "Right Hand Batter",
    country: "southafrica",
    matches: 248,
    totalRuns: 8094,
    highestScore: 175,
    catches: 108,
    fours: 830,
    sixes: 128,
    fifties: 37,
    hundreds: 21,
    wickets: 3,
    economy: 5,
    battingAverage: 36,
    battingStrikeRate: 83,
    highestBowlingSpeed: "121 km/h"
},
 
{
    id: 37,
    name: "Jacques Kallis",
    type: "Batting All-Rounder",
    othertype: "Top Order Batter",
    handtype: "Right Hand Batter / Right Arm Fast Medium",
    country: "southafrica",
    matches: 328,
    totalRuns: 11579,
    highestScore: 139,
    catches: 131,
    fours: 970,
    sixes: 137,
    fifties: 86,
    hundreds: 17,
    wickets: 273,
    economy: 4.45,
    battingAverage: 44,
    battingStrikeRate: 73,
    highestBowlingSpeed: "140 km/h"
},
 
{
    id: 38,
    name: "Daniel Vettori",
    type: "Spin Bowling All-Rounder",
    othertype: "Lower Order Batter",
    handtype: "Left Hand Batter / Left Arm Spin",
    country: "newzealand",
    matches: 295,
    totalRuns: 2253,
    highestScore: 83,
    catches: 83,
    fours: 160,
    sixes: 30,
    fifties: 4,
    hundreds: 0,
    wickets: 305,
    economy: 4.1,
    battingAverage: 17,
    battingStrikeRate: 76,
    highestBowlingSpeed: "118 km/h"
},
 
{
    id: 39,
    name: "Mashrafe Mortaza",
    type: "Fast Bowler",
    othertype: "Lower Order Batter",
    handtype: "Right Hand Batter / Right Arm Fast",
    country: "bangladesh",
    matches: 220,
    totalRuns: 1787,
    highestScore: 51,
    catches: 53,
    fours: 130,
    sixes: 30,
    fifties: 1,
    hundreds: 0,
    wickets: 270,
    economy: 4.96,
    battingAverage: 14,
    battingStrikeRate: 83,
    highestBowlingSpeed: "145 km/h"
},
 
{
    id: 40,
    name: "Shaun Pollock",
    type: "Bowling All-Rounder",
    othertype: "Lower Order Batter",
    handtype: "Right Hand Batter / Right Arm Fast Medium",
    country: "southafrica",
    matches: 303,
    totalRuns: 3519,
    highestScore: 130,
    catches: 108,
    fours: 280,
    sixes: 50,
    fifties: 14,
    hundreds: 1,
    wickets: 393,
    economy: 3.67,
    battingAverage: 26,
    battingStrikeRate: 76,
    highestBowlingSpeed: "138 km/h"
},
 
{
    id: 41,
    name: "Brendon McCullum",
    type: "Wicket-Keeper Batter",
    othertype: "Opening Batter",
    handtype: "Right Hand Batter",
    country: "newzealand",
    matches: 260,
    totalRuns: 6083,
    highestScore: 166,
    catches: 227,
    fours: 600,
    sixes: 200,
    fifties: 32,
    hundreds: 5,
    wickets: 0,
    economy: 0,
    battingAverage: 30,
    battingStrikeRate: 96,
    highestBowlingSpeed: "0 km/h"
},
 
{
    id: 42,
    name: "Yuvraj Singh",
    type: "Batting All-Rounder",
    othertype: "Middle Order Batter",
    handtype: "Left Hand Batter / Slow Left Arm",
    country: "india",
    matches: 304,
    totalRuns: 8701,
    highestScore: 150,
    catches: 94,
    fours: 880,
    sixes: 155,
    fifties: 52,
    hundreds: 14,
    wickets: 111,
    economy: 5.1,
    battingAverage: 36,
    battingStrikeRate: 87,
    highestBowlingSpeed: "129 km/h"
},
 
{
    id: 43,
    name: "Virender Sehwag",
    type: "Opening Batter",
    othertype: "Part Time Off Spinner",
    handtype: "Right Hand Batter / Right Arm Off Spin",
    country: "india",
    matches: 251,
    totalRuns: 8273,
    highestScore: 219,
    catches: 92,
    fours: 1132,
    sixes: 136,
    fifties: 38,
    hundreds: 15,
    wickets: 96,
    economy: 5.4,
    battingAverage: 35,
    battingStrikeRate: 104,
    highestBowlingSpeed: "122 km/h"
},
 
{
    id: 44,
    name: "Zaheer Khan",
    type: "Fast Bowler",
    othertype: "Lower Order Batter",
    handtype: "Left Hand Batter / Left Arm Fast",
    country: "india",
    matches: 200,
    totalRuns: 792,
    highestScore: 34,
    catches: 47,
    fours: 70,
    sixes: 12,
    fifties: 0,
    hundreds: 0,
    wickets: 282,
    economy: 4.93,
    battingAverage: 9,
    battingStrikeRate: 69,
    highestBowlingSpeed: "145 km/h"
},
 
{
    id: 45,
    name: "Makhaya Ntini",
    type: "Fast Bowler",
    othertype: "Tailender",
    handtype: "Right Hand Batter / Right Arm Fast",
    country: "southafrica",
    matches: 173,
    totalRuns: 199,
    highestScore: 42,
    catches: 28,
    fours: 15,
    sixes: 2,
    fifties: 0,
    hundreds: 0,
    wickets: 266,
    economy: 4.6,
    battingAverage: 8,
    battingStrikeRate: 54,
    highestBowlingSpeed: "148 km/h"
},
 
{
    id: 46,
    name: "Kumar Sangakkara",
    type: "Wicket-Keeper Batter",
    othertype: "captain",
    handtype: "Left Hand Batter",
    country: "srilanka",
    matches: 404,
    totalRuns: 14234,
    highestScore: 169,
    catches: 383,
    fours: 1385,
    sixes: 88,
    fifties: 93,
    hundreds: 25,
    wickets: 0,
    economy: 0,
    battingAverage: 41,
    battingStrikeRate: 78,
    highestBowlingSpeed: "0 km/h"
},
 
{
    id: 47,
    name: "Mahela Jayawardene",
    type: "Top Order Batter",
    othertype: "Middle Order Batter",
    handtype: "Right Hand Batter",
    country: "srilanka",
    matches: 448,
    totalRuns: 12650,
    highestScore: 144,
    catches: 218,
    fours: 1290,
    sixes: 91,
    fifties: 77,
    hundreds: 19,
    wickets: 8,
    economy: 5.3,
    battingAverage: 33,
    battingStrikeRate: 78,
    highestBowlingSpeed: "112 km/h"
},
 
{
    id: 48,
    name: "Shoaib Malik",
    type: "Batting All-Rounder",
    othertype: "Middle Order Batter",
    handtype: "Right Hand Batter / Right Arm Off Spin",
    country: "pakistan",
    matches: 287,
    totalRuns: 7534,
    highestScore: 143,
    catches: 90,
    fours: 640,
    sixes: 120,
    fifties: 44,
    hundreds: 9,
    wickets: 158,
    economy: 4.7,
    battingAverage: 34,
    battingStrikeRate: 82,
    highestBowlingSpeed: "126 km/h"
},
 
{
    id: 49,
    name: "MS Dhoni",
    type: "Wicket-Keeper Batter",
    othertype: "captain",
    handtype: "Right Hand Batter",
    country: "india",
    matches: 350,
    totalRuns: 10773,
    highestScore: 183,
    catches: 321,
    fours: 826,
    sixes: 229,
    fifties: 73,
    hundreds: 10,
    wickets: 1,
    economy: 5,
    battingAverage: 50,
    battingStrikeRate: 87,
    highestBowlingSpeed: "120 km/h"
},
 
{
    id: 50,
    name: "Abdul Razzaq",
    type: "All-Rounder",
    othertype: "Lower Order Batter",
    handtype: "Right Hand Batter / Right Arm Fast Medium",
    country: "pakistan",
    matches: 265,
    totalRuns: 5080,
    highestScore: 112,
    catches: 47,
    fours: 420,
    sixes: 95,
    fifties: 23,
    hundreds: 3,
    wickets: 269,
    economy: 4.7,
    battingAverage: 29,
    battingStrikeRate: 81,
    highestBowlingSpeed: "138 km/h"
},
 
{
    id: 51,
    name: "Lasith Malinga",
    type: "Fast Bowler",
    othertype: "Tailender",
    handtype: "Right Hand Batter / Right Arm Fast",
    country: "srilanka",
    matches: 226,
    totalRuns: 567,
    highestScore: 56,
    catches: 40,
    fours: 50,
    sixes: 12,
    fifties: 0,
    hundreds: 0,
    wickets: 338,
    economy: 5.28,
    battingAverage: 8,
    battingStrikeRate: 61,
    highestBowlingSpeed: "155 km/h"
},
 
{
    id: 52,
    name: "Tillakaratne Dilshan",
    type: "Batting All-Rounder",
    othertype: "Opening Batter",
    handtype: "Right Hand Batter / Right Arm Off Spin",
    country: "srilanka",
    matches: 330,
    totalRuns: 10290,
    highestScore: 161,
    catches: 120,
    fours: 1000,
    sixes: 100,
    fifties: 47,
    hundreds: 22,
    wickets: 106,
    economy: 4.9,
    battingAverage: 39,
    battingStrikeRate: 86,
    highestBowlingSpeed: "125 km/h"
},
 
{
    id: 53,
    name: "Shoaib Akhtar",
    type: "Fast Bowler",
    othertype: "Tailender",
    handtype: "Right Hand Batter / Right Arm Fast",
    country: "pakistan",
    matches: 163,
    totalRuns: 394,
    highestScore: 43,
    catches: 14,
    fours: 35,
    sixes: 8,
    fifties: 0,
    hundreds: 0,
    wickets: 247,
    economy: 4.76,
    battingAverage: 7,
    battingStrikeRate: 58,
    highestBowlingSpeed: "161 km/h"
},
 
{
    id: 54,
    name: "Hashim Amla",
    type: "Top Order Batter",
    othertype: "Opening Batter",
    handtype: "Right Hand Batter",
    country: "southafrica",
    matches: 181,
    totalRuns: 8113,
    highestScore: 159,
    catches: 84,
    fours: 830,
    sixes: 50,
    fifties: 39,
    hundreds: 27,
    wickets: 0,
    economy: 0,
    battingAverage: 49,
    battingStrikeRate: 88,
    highestBowlingSpeed: "0 km/h"
},
 
{
    id: 55,
    name: "Ross Taylor",
    type: "Middle Order Batter",
    othertype: "Finisher",
    handtype: "Right Hand Batter",
    country: "newzealand",
    matches: 236,
    totalRuns: 8607,
    highestScore: 181,
    catches: 142,
    fours: 720,
    sixes: 130,
    fifties: 51,
    hundreds: 21,
    wickets: 0,
    economy: 0,
    battingAverage: 47,
    battingStrikeRate: 83,
    highestBowlingSpeed: "0 km/h"
},
 
{
    id: 56,
    name: "James Anderson",
    type: "Fast Bowler",
    othertype: "Tailender",
    handtype: "Left Hand Batter / Right Arm Fast",
    country: "england",
    matches: 194,
    totalRuns: 273,
    highestScore: 28,
    catches: 53,
    fours: 20,
    sixes: 3,
    fifties: 0,
    hundreds: 0,
    wickets: 269,
    economy: 4.92,
    battingAverage: 9,
    battingStrikeRate: 52,
    highestBowlingSpeed: "141 km/h"
},
 
{
    id: 57,
    name: "Chris Gayle",
    type: "Batting All-Rounder",
    othertype: "Opening Batter",
    handtype: "Left Hand Batter / Right Arm Off Spin",
    country: "westindies",
    matches: 301,
    totalRuns: 10480,
    highestScore: 215,
    catches: 124,
    fours: 1128,
    sixes: 331,
    fifties: 54,
    hundreds: 25,
    wickets: 167,
    economy: 5.2,
    battingAverage: 37,
    battingStrikeRate: 87,
    highestBowlingSpeed: "130 km/h"
},
 
{
    id: 58,
    name: "Ajit Agarkar",
    type: "Bowling All-Rounder",
    othertype: "Lower Order Batter",
    handtype: "Right Hand Batter / Right Arm Fast",
    country: "india",
    matches: 191,
    totalRuns: 1269,
    highestScore: 95,
    catches: 41,
    fours: 110,
    sixes: 25,
    fifties: 3,
    hundreds: 0,
    wickets: 288,
    economy: 5.07,
    battingAverage: 14,
    battingStrikeRate: 80,
    highestBowlingSpeed: "140 km/h"
},
 
{
    id: 59,
    name: "Virat Kohli",
    type: "Top Order Batter",
    othertype: "captain",
    handtype: "Right Hand Batter",
    country: "india",
    matches: 300,
    totalRuns: 14085,
    highestScore: 183,
    catches: 158,
    fours: 1310,
    sixes: 152,
    fifties: 74,
    hundreds: 51,
    wickets: 5,
    economy: 6.2,
    battingAverage: 58,
    battingStrikeRate: 93,
    highestBowlingSpeed: "120 km/h"
},
 
{
    id: 60,
    name: "AB de Villiers",
    type: "Wicket-Keeper Batter",
    othertype: "captain",
    handtype: "Right Hand Batter",
    country: "southafrica",
    matches: 228,
    totalRuns: 9577,
    highestScore: 176,
    catches: 176,
    fours: 840,
    sixes: 204,
    fifties: 53,
    hundreds: 25,
    wickets: 7,
    economy: 6,
    battingAverage: 53,
    battingStrikeRate: 101,
    highestBowlingSpeed: "120 km/h"
},
 
{
    id: 61,
    name: "Kevin Pietersen",
    type: "Top Order Batter",
    othertype: "Middle Order Batter",
    handtype: "Right Hand Batter / Right Arm Off Spin",
    country: "england",
    matches: 136,
    totalRuns: 4440,
    highestScore: 130,
    catches: 53,
    fours: 440,
    sixes: 75,
    fifties: 25,
    hundreds: 9,
    wickets: 7,
    economy: 6.4,
    battingAverage: 40,
    battingStrikeRate: 87,
    highestBowlingSpeed: "95 km/h"
},
 
{
    id: 62,
    name: "Mohammad Yousuf",
    type: "Top Order Batter",
    othertype: "Middle Order Batter",
    handtype: "Right Hand Batter",
    country: "pakistan",
    matches: 288,
    totalRuns: 9720,
    highestScore: 141,
    catches: 57,
    fours: 960,
    sixes: 80,
    fifties: 64,
    hundreds: 15,
    wickets: 2,
    economy: 5.3,
    battingAverage: 41,
    battingStrikeRate: 75,
    highestBowlingSpeed: "110 km/h"
},
 
{
    id: 63,
    name: "Rohit Sharma",
    type: "Opening Batter",
    othertype: "captain",
    handtype: "Right Hand Batter",
    country: "india",
    matches: 270,
    totalRuns: 11168,
    highestScore: 264,
    catches: 95,
    fours: 1000,
    sixes: 340,
    fifties: 58,
    hundreds: 32,
    wickets: 8,
    economy: 5.4,
    battingAverage: 49,
    battingStrikeRate: 92,
    highestBowlingSpeed: "125 km/h"
},
 
{
    id: 64,
    name: "Shivnarine Chanderpaul",
    type: "Middle Order Batter",
    othertype: "Part Time Spinner",
    handtype: "Left Hand Batter",
    country: "westindies",
    matches: 268,
    totalRuns: 8778,
    highestScore: 150,
    catches: 75,
    fours: 720,
    sixes: 60,
    fifties: 59,
    hundreds: 11,
    wickets: 14,
    economy: 5,
    battingAverage: 41,
    battingStrikeRate: 70,
    highestBowlingSpeed: "110 km/h"
},
 
{
    id: 65,
    name: "Brett Lee",
    type: "Fast Bowler",
    othertype: "Lower Order Batter",
    handtype: "Right Hand Batter / Right Arm Fast",
    country: "australia",
    matches: 221,
    totalRuns: 1176,
    highestScore: 57,
    catches: 62,
    fours: 90,
    sixes: 25,
    fifties: 1,
    hundreds: 0,
    wickets: 380,
    economy: 4.76,
    battingAverage: 16,
    battingStrikeRate: 85,
    highestBowlingSpeed: "161 km/h"
},
 
{
    id: 66,
    name: "Hansie Cronje",
    type: "All-Rounder",
    othertype: "Middle Order Batter",
    handtype: "Right Hand Batter / Right Arm Medium",
    country: "southafrica",
    matches: 188,
    totalRuns: 5565,
    highestScore: 112,
    catches: 65,
    fours: 480,
    sixes: 50,
    fifties: 39,
    hundreds: 2,
    wickets: 114,
    economy: 4.9,
    battingAverage: 38,
    battingStrikeRate: 79,
    highestBowlingSpeed: "128 km/h"
},
 
{
    id: 67,
    name: "Ravindra Jadeja",
    type: "Bowling All-Rounder",
    othertype: "Left Arm Spinner",
    handtype: "Left Hand Batter",
    country: "india",
    matches: 197,
    totalRuns: 2756,
    highestScore: 87,
    catches: 88,
    fours: 220,
    sixes: 50,
    fifties: 13,
    hundreds: 0,
    wickets: 220,
    economy: 4.9,
    battingAverage: 32,
    battingStrikeRate: 85,
    highestBowlingSpeed: "135 km/h"
},
    {
    id: 68,
    name: "Alec Stewart",
    type: "Wicket-Keeper Batter",
    othertype: "captain",
    handtype: "Right Hand Batter",
    country: "england",
    matches: 170,
    totalRuns: 4677,
    highestScore: 116,
    catches: 174,
    fours: 460,
    sixes: 20,
    fifties: 28,
    hundreds: 4,
    wickets: 0,
    economy: 0,
    battingAverage: 31,
    battingStrikeRate: 72,
    highestBowlingSpeed: "0 km/h"
},
 
{
    id: 69,
    name: "Henry Olonga",
    type: "Fast Bowler",
    othertype: "Tailender",
    handtype: "Right Hand Batter / Right Arm Fast",
    country: "zimbabwe",
    matches: 50,
    totalRuns: 90,
    highestScore: 16,
    catches: 10,
    fours: 8,
    sixes: 2,
    fifties: 0,
    hundreds: 0,
    wickets: 58,
    economy: 5.5,
    battingAverage: 5,
    battingStrikeRate: 60,
    highestBowlingSpeed: "145 km/h"
},
 
{
    id: 70,
    name: "Dale Steyn",
    type: "Fast Bowler",
    othertype: "Tailender",
    handtype: "Right Hand Batter / Right Arm Fast",
    country: "southafrica",
    matches: 125,
    totalRuns: 305,
    highestScore: 60,
    catches: 35,
    fours: 25,
    sixes: 6,
    fifties: 1,
    hundreds: 0,
    wickets: 196,
    economy: 4.9,
    battingAverage: 8,
    battingStrikeRate: 78,
    highestBowlingSpeed: "155 km/h"
},
 
{
    id: 71,
    name: "Quinton de Kock",
    type: "Wicket-Keeper Batter",
    othertype: "Opening Batter",
    handtype: "Left Hand Batter",
    country: "southafrica",
    matches: 155,
    totalRuns: 6770,
    highestScore: 178,
    catches: 230,
    fours: 700,
    sixes: 120,
    fifties: 30,
    hundreds: 21,
    wickets: 0,
    economy: 0,
    battingAverage: 45,
    battingStrikeRate: 97,
    highestBowlingSpeed: "0 km/h"
},
 
{
    id: 72,
    name: "Andy Flower",
    type: "Wicket-Keeper Batter",
    othertype: "captain",
    handtype: "Left Hand Batter",
    country: "zimbabwe",
    matches: 213,
    totalRuns: 6786,
    highestScore: 145,
    catches: 141,
    fours: 600,
    sixes: 30,
    fifties: 55,
    hundreds: 4,
    wickets: 0,
    economy: 0,
    battingAverage: 35,
    battingStrikeRate: 74,
    highestBowlingSpeed: "0 km/h"
},
 
{
    id: 73,
    name: "Gordon Greenidge",
    type: "Opening Batter",
    othertype: "Top Order Batter",
    handtype: "Right Hand Batter",
    country: "westindies",
    matches: 128,
    totalRuns: 5134,
    highestScore: 133,
    catches: 45,
    fours: 480,
    sixes: 35,
    fifties: 31,
    hundreds: 11,
    wickets: 0,
    economy: 0,
    battingAverage: 45,
    battingStrikeRate: 65,
    highestBowlingSpeed: "0 km/h"
},
 
{
    id: 74,
    name: "Sean Williams",
    type: "Batting All-Rounder",
    othertype: "Middle Order Batter",
    handtype: "Left Hand Batter / Slow Left Arm",
    country: "zimbabwe",
    matches: 156,
    totalRuns: 4955,
    highestScore: 129,
    catches: 70,
    fours: 420,
    sixes: 60,
    fifties: 32,
    hundreds: 5,
    wickets: 67,
    economy: 4.8,
    battingAverage: 38,
    battingStrikeRate: 78,
    highestBowlingSpeed: "92 km/h"
},
 
{
    id: 75,
    name: "Graeme Smith",
    type: "Opening Batter",
    othertype: "captain",
    handtype: "Left Hand Batter / Right Arm Off Spin",
    country: "southafrica",
    matches: 197,
    totalRuns: 6989,
    highestScore: 141,
    catches: 90,
    fours: 720,
    sixes: 65,
    fifties: 47,
    hundreds: 10,
    wickets: 18,
    economy: 5.1,
    battingAverage: 38,
    battingStrikeRate: 80,
    highestBowlingSpeed: "112 km/h"
},
 
{
    id: 76,
    name: "Mustafizur Rahman",
    type: "Fast Bowler",
    othertype: "Tailender",
    handtype: "Left Hand Batter / Left Arm Fast Medium",
    country: "bangladesh",
    matches: 109,
    totalRuns: 130,
    highestScore: 18,
    catches: 25,
    fours: 10,
    sixes: 2,
    fifties: 0,
    hundreds: 0,
    wickets: 178,
    economy: 5.2,
    battingAverage: 5,
    battingStrikeRate: 60,
    highestBowlingSpeed: "140 km/h"
},
 
{
    id: 77,
    name: "Elton Chigumbura",
    type: "Bowling All-Rounder",
    othertype: "captain",
    handtype: "Right Hand Batter / Right Arm Medium Fast",
    country: "zimbabwe",
    matches: 213,
    totalRuns: 4112,
    highestScore: 117,
    catches: 75,
    fours: 320,
    sixes: 90,
    fifties: 17,
    hundreds: 2,
    wickets: 105,
    economy: 5.4,
    battingAverage: 24,
    battingStrikeRate: 82,
    highestBowlingSpeed: "130 km/h"
},
 
{
    id: 78,
    name: "Clive Lloyd",
    type: "Middle Order Batter",
    othertype: "captain",
    handtype: "Left Hand Batter",
    country: "westindies",
    matches: 87,
    totalRuns: 1977,
    highestScore: 102,
    catches: 39,
    fours: 180,
    sixes: 25,
    fifties: 11,
    hundreds: 1,
    wickets: 8,
    economy: 4.3,
    battingAverage: 39,
    battingStrikeRate: 81,
    highestBowlingSpeed: "118 km/h"
},
 
{
    id: 79,
    name: "Ian Botham",
    type: "Bowling All-Rounder",
    othertype: "Lower Order Batter",
    handtype: "Right Hand Batter / Right Arm Fast Medium",
    country: "england",
    matches: 116,
    totalRuns: 2113,
    highestScore: 79,
    catches: 36,
    fours: 200,
    sixes: 40,
    fifties: 9,
    hundreds: 0,
    wickets: 145,
    economy: 3.9,
    battingAverage: 24,
    battingStrikeRate: 79,
    highestBowlingSpeed: "135 km/h"
},
 
{
    id: 80,
    name: "Upul Tharanga",
    type: "Opening Batter",
    othertype: "captain",
    handtype: "Left Hand Batter",
    country: "srilanka",
    matches: 235,
    totalRuns: 6951,
    highestScore: 174,
    catches: 60,
    fours: 720,
    sixes: 55,
    fifties: 37,
    hundreds: 15,
    wickets: 0,
    economy: 0,
    battingAverage: 33,
    battingStrikeRate: 77,
    highestBowlingSpeed: "0 km/h"
},
 
{
    id: 81,
    name: "Tatenda Taibu",
    type: "Wicket-Keeper Batter",
    othertype: "captain",
    handtype: "Right Hand Batter",
    country: "zimbabwe",
    matches: 150,
    totalRuns: 3393,
    highestScore: 107,
    catches: 120,
    fours: 300,
    sixes: 15,
    fifties: 23,
    hundreds: 1,
    wickets: 0,
    economy: 0,
    battingAverage: 28,
    battingStrikeRate: 67,
    highestBowlingSpeed: "0 km/h"
},
 
{
    id: 82,
    name: "Graham Gooch",
    type: "Opening Batter",
    othertype: "captain",
    handtype: "Right Hand Batter / Right Arm Medium",
    country: "england",
    matches: 125,
    totalRuns: 4290,
    highestScore: 142,
    catches: 45,
    fours: 420,
    sixes: 20,
    fifties: 23,
    hundreds: 8,
    wickets: 36,
    economy: 4.6,
    battingAverage: 36,
    battingStrikeRate: 70,
    highestBowlingSpeed: "118 km/h"
},
 
{
    id: 83,
    name: "Neil Johnson",
    type: "Batting All-Rounder",
    othertype: "Opening Batter",
    handtype: "Left Hand Batter / Right Arm Medium",
    country: "zimbabwe",
    matches: 48,
    totalRuns: 1679,
    highestScore: 132,
    catches: 25,
    fours: 180,
    sixes: 20,
    fifties: 11,
    hundreds: 4,
    wickets: 47,
    economy: 4.7,
    battingAverage: 37,
    battingStrikeRate: 80,
    highestBowlingSpeed: "128 km/h"
},
 
{
    id: 84,
    name: "Brendan Taylor",
    type: "Wicket-Keeper Batter",
    othertype: "captain",
    handtype: "Right Hand Batter",
    country: "zimbabwe",
    matches: 205,
    totalRuns: 6677,
    highestScore: 145,
    catches: 150,
    fours: 600,
    sixes: 60,
    fifties: 39,
    hundreds: 11,
    wickets: 9,
    economy: 5.8,
    battingAverage: 35,
    battingStrikeRate: 76,
    highestBowlingSpeed: "108 km/h"
},
 
{
    id: 85,
    name: "Kane Williamson",
    type: "Top Order Batter",
    othertype: "captain",
    handtype: "Right Hand Batter / Right Arm Off Spin",
    country: "newzealand",
    matches: 165,
    totalRuns: 6554,
    highestScore: 148,
    catches: 75,
    fours: 600,
    sixes: 45,
    fifties: 42,
    hundreds: 13,
    wickets: 37,
    economy: 5.3,
    battingAverage: 47,
    battingStrikeRate: 81,
    highestBowlingSpeed: "112 km/h"
},
 
{
    id: 86,
    name: "Angelo Mathews",
    type: "Batting All-Rounder",
    othertype: "captain",
    handtype: "Right Hand Batter / Right Arm Medium",
    country: "srilanka",
    matches: 226,
    totalRuns: 5835,
    highestScore: 139,
    catches: 70,
    fours: 440,
    sixes: 70,
    fifties: 39,
    hundreds: 3,
    wickets: 120,
    economy: 5,
    battingAverage: 41,
    battingStrikeRate: 82,
    highestBowlingSpeed: "132 km/h"
},
 
{
    id: 87,
    name: "Mohammad Rafique",
    type: "Spin Bowling All-Rounder",
    othertype: "Lower Order Batter",
    handtype: "Left Hand Batter / Slow Left Arm",
    country: "bangladesh",
    matches: 125,
    totalRuns: 1191,
    highestScore: 77,
    catches: 30,
    fours: 110,
    sixes: 25,
    fifties: 3,
    hundreds: 0,
    wickets: 119,
    economy: 4.4,
    battingAverage: 13,
    battingStrikeRate: 82,
    highestBowlingSpeed: "85 km/h"
},
 
{
    id: 88,
    name: "Michael Holding",
    type: "Fast Bowler",
    othertype: "Tailender",
    handtype: "Right Hand Batter / Right Arm Fast",
    country: "westindies",
    matches: 102,
    totalRuns: 282,
    highestScore: 64,
    catches: 30,
    fours: 22,
    sixes: 5,
    fifties: 1,
    hundreds: 0,
    wickets: 142,
    economy: 3.3,
    battingAverage: 9,
    battingStrikeRate: 70,
    highestBowlingSpeed: "155 km/h"
},
 
{
    id: 89,
    name: "Alistair Campbell",
    type: "Top Order Batter",
    othertype: "captain",
    handtype: "Left Hand Batter",
    country: "zimbabwe",
    matches: 188,
    totalRuns: 5185,
    highestScore: 131,
    catches: 80,
    fours: 460,
    sixes: 30,
    fifties: 30,
    hundreds: 7,
    wickets: 4,
    economy: 5.4,
    battingAverage: 30,
    battingStrikeRate: 67,
    highestBowlingSpeed: "108 km/h"
},
 
{
    id: 90,
    name: "Heath Streak",
    type: "Bowling All-Rounder",
    othertype: "captain",
    handtype: "Right Hand Batter / Right Arm Fast Medium",
    country: "zimbabwe",
    matches: 189,
    totalRuns: 2943,
    highestScore: 79,
    catches: 50,
    fours: 240,
    sixes: 35,
    fifties: 13,
    hundreds: 0,
    wickets: 239,
    economy: 4.5,
    battingAverage: 28,
    battingStrikeRate: 75,
    highestBowlingSpeed: "140 km/h"
},
 
{
    id: 91,
    name: "Mahmudullah",
    type: "Batting All-Rounder",
    othertype: "Finisher",
    handtype: "Right Hand Batter / Right Arm Off Spin",
    country: "bangladesh",
    matches: 232,
    totalRuns: 5689,
    highestScore: 128,
    catches: 80,
    fours: 420,
    sixes: 90,
    fifties: 33,
    hundreds: 4,
    wickets: 84,
    economy: 5.2,
    battingAverage: 36,
    battingStrikeRate: 77,
    highestBowlingSpeed: "112 km/h"
},
 
{
    id: 92,
    name: "Mitchell Starc",
    type: "Fast Bowler",
    othertype: "Lower Order Batter",
    handtype: "Left Hand Batter / Left Arm Fast",
    country: "australia",
    matches: 121,
    totalRuns: 555,
    highestScore: 52,
    catches: 35,
    fours: 45,
    sixes: 15,
    fifties: 1,
    hundreds: 0,
    wickets: 244,
    economy: 5.2,
    battingAverage: 13,
    battingStrikeRate: 90,
    highestBowlingSpeed: "160 km/h"
},
 
{
    id: 93,
    name: "Andrew Flintoff",
    type: "Bowling All-Rounder",
    othertype: "Finisher",
    handtype: "Right Hand Batter / Right Arm Fast",
    country: "england",
    matches: 141,
    totalRuns: 3394,
    highestScore: 123,
    catches: 50,
    fours: 280,
    sixes: 80,
    fifties: 18,
    hundreds: 3,
    wickets: 169,
    economy: 4.5,
    battingAverage: 32,
    battingStrikeRate: 89,
    highestBowlingSpeed: "145 km/h"
},
 
{
    id: 94,
    name: "Alastair Cook",
    type: "Opening Batter",
    othertype: "captain",
    handtype: "Left Hand Batter",
    country: "england",
    matches: 92,
    totalRuns: 3204,
    highestScore: 137,
    catches: 36,
    fours: 320,
    sixes: 15,
    fifties: 19,
    hundreds: 5,
    wickets: 0,
    economy: 0,
    battingAverage: 37,
    battingStrikeRate: 77,
    highestBowlingSpeed: "0 km/h"
},
 
{
    id: 95,
    name: "Stephen Fleming",
    type: "Top Order Batter",
    othertype: "captain",
    handtype: "Left Hand Batter",
    country: "newzealand",
    matches: 280,
    totalRuns: 8037,
    highestScore: 134,
    catches: 133,
    fours: 740,
    sixes: 40,
    fifties: 49,
    hundreds: 8,
    wickets: 1,
    economy: 5.5,
    battingAverage: 32,
    battingStrikeRate: 71,
    highestBowlingSpeed: "108 km/h"
},
 
{
    id: 96,
    name: "Mohammad Ashraful",
    type: "Middle Order Batter",
    othertype: "Part Time Leg Spinner",
    handtype: "Right Hand Batter / Right Arm Leg Spin",
    country: "bangladesh",
    matches: 177,
    totalRuns: 3468,
    highestScore: 109,
    catches: 40,
    fours: 340,
    sixes: 40,
    fifties: 20,
    hundreds: 3,
    wickets: 18,
    economy: 5.3,
    battingAverage: 22,
    battingStrikeRate: 70,
    highestBowlingSpeed: "108 km/h"
},
 
{
    id: 97,
    name: "Eoin Morgan",
    type: "Middle Order Batter",
    othertype: "captain",
    handtype: "Left Hand Batter",
    country: "england",
    matches: 248,
    totalRuns: 7701,
    highestScore: 148,
    catches: 90,
    fours: 620,
    sixes: 220,
    fifties: 47,
    hundreds: 14,
    wickets: 0,
    economy: 0,
    battingAverage: 39,
    battingStrikeRate: 91,
    highestBowlingSpeed: "0 km/h"
},
 
{
    id: 98,
    name: "Mushfiqur Rahim",
    type: "Wicket-Keeper Batter",
    othertype: "Middle Order Batter",
    handtype: "Right Hand Batter",
    country: "bangladesh",
    matches: 274,
    totalRuns: 7795,
    highestScore: 144,
    catches: 240,
    fours: 660,
    sixes: 60,
    fifties: 49,
    hundreds: 9,
    wickets: 0,
    economy: 0,
    battingAverage: 37,
    battingStrikeRate: 79,
    highestBowlingSpeed: "0 km/h"
},
 
{
    id: 99,
    name: "Arjuna Ranatunga",
    type: "Middle Order Batter",
    othertype: "captain",
    handtype: "Right Hand Batter / Right Arm Medium",
    country: "srilanka",
    matches: 269,
    totalRuns: 7456,
    highestScore: 131,
    catches: 63,
    fours: 600,
    sixes: 40,
    fifties: 49,
    hundreds: 4,
    wickets: 79,
    economy: 4.8,
    battingAverage: 35,
    battingStrikeRate: 77,
    highestBowlingSpeed: "118 km/h"
},
 
{
    id: 100,
    name: "Marvan Atapattu",
    type: "Opening Batter",
    othertype: "captain",
    handtype: "Right Hand Batter",
    country: "srilanka",
    matches: 268,
    totalRuns: 8529,
    highestScore: 132,
    catches: 80,
    fours: 760,
    sixes: 35,
    fifties: 59,
    hundreds: 11,
    wickets: 0,
    economy: 0,
    battingAverage: 37,
    battingStrikeRate: 70,
    highestBowlingSpeed: "0 km/h"
},
 
{
    id: 101,
    name: "Dwayne Bravo",
    type: "Bowling All-Rounder",
    othertype: "Finisher",
    handtype: "Right Hand Batter / Right Arm Medium Fast",
    country: "westindies",
    matches: 164,
    totalRuns: 2968,
    highestScore: 112,
    catches: 70,
    fours: 250,
    sixes: 80,
    fifties: 10,
    hundreds: 2,
    wickets: 199,
    economy: 5,
    battingAverage: 25,
    battingStrikeRate: 82,
    highestBowlingSpeed: "135 km/h"
},
 
{
    id: 102,
    name: "Allan Border",
    type: "Middle Order Batter",
    othertype: "captain",
    handtype: "Left Hand Batter / Slow Left Arm",
    country: "australia",
    matches: 273,
    totalRuns: 6524,
    highestScore: 127,
    catches: 127,
    fours: 540,
    sixes: 30,
    fifties: 39,
    hundreds: 3,
    wickets: 73,
    economy: 4.6,
    battingAverage: 30,
    battingStrikeRate: 71,
    highestBowlingSpeed: "108 km/h"
},
 
{
    id: 103,
    name: "Hamilton Masakadza",
    type: "Opening Batter",
    othertype: "Part Time Off Spinner",
    handtype: "Right Hand Batter / Right Arm Off Spin",
    country: "zimbabwe",
    matches: 209,
    totalRuns: 5658,
    highestScore: 178,
    catches: 60,
    fours: 540,
    sixes: 55,
    fifties: 30,
    hundreds: 5,
    wickets: 25,
    economy: 5.2,
    battingAverage: 27,
    battingStrikeRate: 73,
    highestBowlingSpeed: "112 km/h"
},
 
{
    id: 104,
    name: "Martin Crowe",
    type: "Middle Order Batter",
    othertype: "captain",
    handtype: "Right Hand Batter / Right Arm Medium",
    country: "newzealand",
    matches: 143,
    totalRuns: 4704,
    highestScore: 107,
    catches: 66,
    fours: 420,
    sixes: 30,
    fifties: 34,
    hundreds: 4,
    wickets: 29,
    economy: 4.7,
    battingAverage: 38,
    battingStrikeRate: 72,
    highestBowlingSpeed: "120 km/h"
},
 
{
    id: 105,
    name: "Martin Guptill",
    type: "Opening Batter",
    othertype: "Top Order Batter",
    handtype: "Right Hand Batter / Right Arm Off Spin",
    country: "newzealand",
    matches: 198,
    totalRuns: 7346,
    highestScore: 237,
    catches: 90,
    fours: 700,
    sixes: 187,
    fifties: 39,
    hundreds: 18,
    wickets: 6,
    economy: 5.2,
    battingAverage: 41,
    battingStrikeRate: 87,
    highestBowlingSpeed: "112 km/h"
},
 
{
    id: 106,
    name: "Joe Root",
    type: "Top Order Batter",
    othertype: "Middle Order Batter",
    handtype: "Right Hand Batter / Right Arm Off Spin",
    country: "england",
    matches: 171,
    totalRuns: 6522,
    highestScore: 133,
    catches: 85,
    fours: 580,
    sixes: 40,
    fifties: 39,
    hundreds: 16,
    wickets: 27,
    economy: 5.5,
    battingAverage: 49,
    battingStrikeRate: 87,
    highestBowlingSpeed: "112 km/h"
},
 
{
    id: 107,
    name: "Nathan Astle",
    type: "Opening Batter",
    othertype: "Bowling All-Rounder",
    handtype: "Right Hand Batter / Right Arm Medium",
    country: "newzealand",
    matches: 223,
    totalRuns: 7090,
    highestScore: 145,
    catches: 83,
    fours: 700,
    sixes: 80,
    fifties: 41,
    hundreds: 16,
    wickets: 99,
    economy: 4.9,
    battingAverage: 35,
    battingStrikeRate: 73,
    highestBowlingSpeed: "122 km/h"
},
 
{
    id: 108,
    name: "Tim Southee",
    type: "Fast Bowler",
    othertype: "Lower Order Batter",
    handtype: "Right Hand Batter / Right Arm Fast Medium",
    country: "newzealand",
    matches: 161,
    totalRuns: 720,
    highestScore: 55,
    catches: 60,
    fours: 60,
    sixes: 30,
    fifties: 1,
    hundreds: 0,
    wickets: 221,
    economy: 5.4,
    battingAverage: 11,
    battingStrikeRate: 110,
    highestBowlingSpeed: "140 km/h"
},
 
{
    id: 109,
    name: "Habibul Bashar",
    type: "Middle Order Batter",
    othertype: "captain",
    handtype: "Right Hand Batter",
    country: "bangladesh",
    matches: 111,
    totalRuns: 2168,
    highestScore: 78,
    catches: 30,
    fours: 230,
    sixes: 8,
    fifties: 14,
    hundreds: 0,
    wickets: 0,
    economy: 0,
    battingAverage: 21,
    battingStrikeRate: 68,
    highestBowlingSpeed: "0 km/h"
},
 
{
    id: 110,
    name: "David Warner",
    type: "Opening Batter",
    othertype: "Top Order Batter",
    handtype: "Left Hand Batter",
    country: "australia",
    matches: 161,
    totalRuns: 6932,
    highestScore: 179,
    catches: 75,
    fours: 700,
    sixes: 135,
    fifties: 33,
    hundreds: 22,
    wickets: 0,
    economy: 0,
    battingAverage: 45,
    battingStrikeRate: 97,
    highestBowlingSpeed: "0 km/h"
},
 
{
    id: 111,
    name: "Steve Smith",
    type: "Top Order Batter",
    othertype: "captain",
    handtype: "Right Hand Batter / Right Arm Leg Spin",
    country: "australia",
    matches: 155,
    totalRuns: 5800,
    highestScore: 164,
    catches: 90,
    fours: 480,
    sixes: 55,
    fifties: 32,
    hundreds: 12,
    wickets: 28,
    economy: 5.9,
    battingAverage: 43,
    battingStrikeRate: 88,
    highestBowlingSpeed: "118 km/h"
},
 
{
    id: 112,
    name: "Shakib Al Hasan",
    type: "Batting All-Rounder",
    othertype: "captain",
    handtype: "Left Hand Batter / Slow Left Arm",
    country: "bangladesh",
    matches: 247,
    totalRuns: 7570,
    highestScore: 134,
    catches: 60,
    fours: 700,
    sixes: 50,
    fifties: 56,
    hundreds: 9,
    wickets: 317,
    economy: 4.6,
    battingAverage: 37,
    battingStrikeRate: 82,
    highestBowlingSpeed: "92 km/h"
},
 
{
    id: 113,
    name: "Abdur Razzak",
    type: "Left Arm Spinner",
    othertype: "Lower Order Batter",
    handtype: "Left Hand Batter / Slow Left Arm",
    country: "bangladesh",
    matches: 153,
    totalRuns: 690,
    highestScore: 33,
    catches: 35,
    fours: 50,
    sixes: 10,
    fifties: 0,
    hundreds: 0,
    wickets: 207,
    economy: 4.6,
    battingAverage: 10,
    battingStrikeRate: 70,
    highestBowlingSpeed: "88 km/h"
},
 
{
    id: 114,
    name: "Jos Buttler",
    type: "Wicket-Keeper Batter",
    othertype: "captain",
    handtype: "Right Hand Batter",
    country: "england",
    matches: 181,
    totalRuns: 5236,
    highestScore: 162,
    catches: 240,
    fours: 420,
    sixes: 180,
    fifties: 27,
    hundreds: 11,
    wickets: 0,
    economy: 0,
    battingAverage: 41,
    battingStrikeRate: 118,
    highestBowlingSpeed: "0 km/h"
},
 
{
    id: 115,
    name: "Trent Boult",
    type: "Fast Bowler",
    othertype: "Tailender",
    handtype: "Right Hand Batter / Left Arm Fast",
    country: "newzealand",
    matches: 114,
    totalRuns: 250,
    highestScore: 21,
    catches: 45,
    fours: 18,
    sixes: 4,
    fifties: 0,
    hundreds: 0,
    wickets: 211,
    economy: 5,
    battingAverage: 7,
    battingStrikeRate: 70,
    highestBowlingSpeed: "145 km/h"
},
 
{
    id: 116,
    name: "Tamim Iqbal",
    type: "Opening Batter",
    othertype: "captain",
    handtype: "Left Hand Batter",
    country: "bangladesh",
    matches: 243,
    totalRuns: 8357,
    highestScore: 158,
    catches: 65,
    fours: 880,
    sixes: 100,
    fifties: 56,
    hundreds: 14,
    wickets: 0,
    economy: 0,
    battingAverage: 36,
    battingStrikeRate: 78,
    highestBowlingSpeed: "0 km/h"
},
 
{
    id: 117,
    name: "Ben Stokes",
    type: "Batting All-Rounder",
    othertype: "Middle Order Batter",
    handtype: "Left Hand Batter / Right Arm Fast Medium",
    country: "england",
    matches: 114,
    totalRuns: 3463,
    highestScore: 182,
    catches: 60,
    fours: 280,
    sixes: 90,
    fifties: 22,
    hundreds: 4,
    wickets: 74,
    economy: 6,
    battingAverage: 39,
    battingStrikeRate: 95,
    highestBowlingSpeed: "140 km/h"
},
 
{
    id: 118,
    name: "Liton Das",
    type: "Wicket-Keeper Batter",
    othertype: "Opening Batter",
    handtype: "Right Hand Batter",
    country: "bangladesh",
    matches: 100,
    totalRuns: 3200,
    highestScore: 176,
    catches: 110,
    fours: 360,
    sixes: 45,
    fifties: 18,
    hundreds: 6,
    wickets: 0,
    economy: 0,
    battingAverage: 35,
    battingStrikeRate: 88,
    highestBowlingSpeed: "0 km/h"
},
 
{
    id: 119,
    name: "Michael Clarke",
    type: "Middle Order Batter",
    othertype: "captain",
    handtype: "Right Hand Batter / Slow Left Arm",
    country: "australia",
    matches: 245,
    totalRuns: 7981,
    highestScore: 130,
    catches: 105,
    fours: 660,
    sixes: 55,
    fifties: 58,
    hundreds: 8,
    wickets: 57,
    economy: 5,
    battingAverage: 44,
    battingStrikeRate: 78,
    highestBowlingSpeed: "115 km/h"
},
 
{
    id: 120,
    name: "Malcolm Marshall",
    type: "Fast Bowler",
    othertype: "Lower Order Batter",
    handtype: "Right Hand Batter / Right Arm Fast",
    country: "westindies",
    matches: 136,
    totalRuns: 955,
    highestScore: 66,
    catches: 15,
    fours: 70,
    sixes: 8,
    fifties: 1,
    hundreds: 0,
    wickets: 157,
    economy: 3.5,
    battingAverage: 14,
    battingStrikeRate: 76,
    highestBowlingSpeed: "150 km/h"
},
 
{
    id: 121,
    name: "Jonty Rhodes",
    type: "Middle Order Batter",
    othertype: "Finisher",
    handtype: "Right Hand Batter",
    country: "southafrica",
    matches: 245,
    totalRuns: 5935,
    highestScore: 121,
    catches: 105,
    fours: 480,
    sixes: 35,
    fifties: 33,
    hundreds: 2,
    wickets: 0,
    economy: 0,
    battingAverage: 35,
    battingStrikeRate: 81,
    highestBowlingSpeed: "0 km/h"
}
];
