const players = [

{
    id: 1,
    name: "Viv Richards",
    type: "Middle Order Batter",
    othertype: "Part Time Off Spinner",
    handtype: "Right Hand Batter",
    country: "westindies",
    matches: 308,
    totalRuns: 15672,
    highestScore: 189,
    catches: 140,
    fours: 1385,
    sixes: 220,
    fifties: 90,
    hundreds: 35,
    wickets: 118,
    economy: 4.5,
    battingAverage: 47,
    battingStrikeRate: 90,
    highestBowlingSpeed: "130 km/h"
},

{
    id: 2,
    name: "Desmond Haynes",
    type: "Opening Batter",
    othertype: "Right Hand Batter",
    handtype: "Right Hand Batter",
    country: "westindies",
    matches: 354,
    totalRuns: 16135,
    highestScore: 152,
    catches: 120,
    fours: 1450,
    sixes: 90,
    fifties: 96,
    hundreds: 25,
    wickets: 5,
    economy: 5.2,
    battingAverage: 42,
    battingStrikeRate: 74,
    highestBowlingSpeed: "118 km/h"
},

{
    id: 3,
    name: "Kapil Dev",
    type: "Fast Bowling All-Rounder",
    othertype: "captain",
    handtype: "Right Hand Batter / Right Arm Fast",
    country: "india",
    matches: 356,
    totalRuns: 9031,
    highestScore: 175,
    catches: 110,
    fours: 750,
    sixes: 130,
    fifties: 39,
    hundreds: 9,
    wickets: 687,
    economy: 3.8,
    battingAverage: 31,
    battingStrikeRate: 95,
    highestBowlingSpeed: "140 km/h"
},

{
    id: 4,
    name: "Imran Khan",
    type: "Fast Bowling All-Rounder",
    othertype: "captain",
    handtype: "Right Hand Batter / Right Arm Fast",
    country: "pakistan",
    matches: 263,
    totalRuns: 7516,
    highestScore: 136,
    catches: 90,
    fours: 620,
    sixes: 85,
    fifties: 30,
    hundreds: 6,
    wickets: 544,
    economy: 3.9,
    battingAverage: 37,
    battingStrikeRate: 88,
    highestBowlingSpeed: "145 km/h"
},

{
    id: 5,
    name: "Richard Hadlee",
    type: "Fast Bowling All-Rounder",
    othertype: "Lower Order Batter",
    handtype: "Right Hand Batter / Right Arm Fast",
    country: "newzealand",
    matches: 197,
    totalRuns: 4312,
    highestScore: 151,
    catches: 85,
    fours: 340,
    sixes: 45,
    fifties: 15,
    hundreds: 2,
    wickets: 589,
    economy: 3.2,
    battingAverage: 27,
    battingStrikeRate: 72,
    highestBowlingSpeed: "142 km/h"
},

{
    id: 6,
    name: "Mohammad Azharuddin",
    type: "Middle Order Batter",
    othertype: "Part Time Off Spinner",
    handtype: "Right Hand Batter",
    country: "india",
    matches: 433,
    totalRuns: 15593,
    highestScore: 199,
    catches: 261,
    fours: 1400,
    sixes: 75,
    fifties: 92,
    hundreds: 29,
    wickets: 12,
    economy: 4.8,
    battingAverage: 45,
    battingStrikeRate: 78,
    highestBowlingSpeed: "122 km/h"
},

{
    id: 7,
    name: "Allan Donald",
    type: "Fast Bowler",
    othertype: "Tailender",
    handtype: "Right Hand Batter / Right Arm Fast",
    country: "southafrica",
    matches: 236,
    totalRuns: 1200,
    highestScore: 30,
    catches: 70,
    fours: 90,
    sixes: 5,
    fifties: 0,
    hundreds: 0,
    wickets: 602,
    economy: 3.9,
    battingAverage: 10,
    battingStrikeRate: 55,
    highestBowlingSpeed: "148 km/h"
},

{
    id: 8,
    name: "Wasim Akram",
    type: "Fast Bowling All-Rounder",
    othertype: "Lower Order Batter",
    handtype: "Left Hand Batter / Left Arm Fast",
    country: "pakistan",
    matches: 460,
    totalRuns: 6615,
    highestScore: 257,
    catches: 120,
    fours: 600,
    sixes: 90,
    fifties: 20,
    hundreds: 3,
    wickets: 916,
    economy: 3.9,
    battingAverage: 22,
    battingStrikeRate: 88,
    highestBowlingSpeed: "150 km/h"
},

{
    id: 9,
    name: "Courtney Walsh",
    type: "Fast Bowler",
    othertype: "Tailender",
    handtype: "Right Hand Batter / Right Arm Fast",
    country: "westindies",
    matches: 337,
    totalRuns: 1200,
    highestScore: 30,
    catches: 95,
    fours: 85,
    sixes: 12,
    fifties: 0,
    hundreds: 0,
    wickets: 746,
    economy: 3.1,
    battingAverage: 9,
    battingStrikeRate: 52,
    highestBowlingSpeed: "145 km/h"
},

{
    id: 10,
    name: "Curtly Ambrose",
    type: "Fast Bowler",
    othertype: "Tailender",
    handtype: "Left Hand Batter / Right Arm Fast",
    country: "westindies",
    matches: 274,
    totalRuns: 900,
    highestScore: 27,
    catches: 80,
    fours: 60,
    sixes: 3,
    fifties: 0,
    hundreds: 0,
    wickets: 630,
    economy: 2.9,
    battingAverage: 8,
    battingStrikeRate: 45,
    highestBowlingSpeed: "146 km/h"
},

{
    id: 11,
    name: "Saeed Anwar",
    type: "Opening Batter",
    othertype: "Left Hand Batter",
    handtype: "Left Hand Batter",
    country: "pakistan",
    matches: 302,
    totalRuns: 11811,
    highestScore: 194,
    catches: 85,
    fours: 1040,
    sixes: 110,
    fifties: 68,
    hundreds: 25,
    wickets: 0,
    economy: 0,
    battingAverage: 39,
    battingStrikeRate: 80,
    highestBowlingSpeed: "0 km/h"
},

{
    id: 12,
    name: "Brian Lara",
    type: "Top Order Batter",
    othertype: "Middle Order Batter",
    handtype: "Left Hand Batter",
    country: "westindies",
    matches: 430,
    totalRuns: 22358,
    highestScore: 400,
    catches: 180,
    fours: 2150,
    sixes: 220,
    fifties: 111,
    hundreds: 53,
    wickets: 4,
    economy: 4.9,
    battingAverage: 52,
    battingStrikeRate: 79,
    highestBowlingSpeed: "118 km/h"
},

{
    id: 13,
    name: "Sachin Tendulkar",
    type: "Batting All-Rounder",
    othertype: "Top Order Batter",
    handtype: "Right Hand Batter",
    country: "india",
    matches: 664,
    totalRuns: 34357,
    highestScore: 248,
    catches: 256,
    fours: 4076,
    sixes: 264,
    fifties: 164,
    hundreds: 100,
    wickets: 201,
    economy: 5.1,
    battingAverage: 48,
    battingStrikeRate: 86,
    highestBowlingSpeed: "134 km/h"
},

{
    id: 14,
    name: "Javagal Srinath",
    type: "Fast Bowler",
    othertype: "Lower Order Batter",
    handtype: "Right Hand Batter / Right Arm Fast",
    country: "india",
    matches: 363,
    totalRuns: 1800,
    highestScore: 76,
    catches: 92,
    fours: 140,
    sixes: 20,
    fifties: 1,
    hundreds: 0,
    wickets: 551,
    economy: 4.3,
    battingAverage: 13,
    battingStrikeRate: 70,
    highestBowlingSpeed: "149 km/h"
},

{
    id: 15,
    name: "Shane Warne",
    type: "Leg Spinner",
    othertype: "Lower Order Batter",
    handtype: "Right Hand Batter / Right Arm Leg Spin",
    country: "australia",
    matches: 339,
    totalRuns: 4172,
    highestScore: 99,
    catches: 125,
    fours: 320,
    sixes: 40,
    fifties: 13,
    hundreds: 0,
    wickets: 1001,
    economy: 3.8,
    battingAverage: 18,
    battingStrikeRate: 72,
    highestBowlingSpeed: "128 km/h"
},

{
    id: 16,
    name: "Inzamam-ul-Haq",
    type: "Middle Order Batter",
    othertype: "captain",
    handtype: "Right Hand Batter",
    country: "pakistan",
    matches: 499,
    totalRuns: 20580,
    highestScore: 329,
    catches: 135,
    fours: 1800,
    sixes: 150,
    fifties: 129,
    hundreds: 35,
    wickets: 3,
    economy: 5.6,
    battingAverage: 49,
    battingStrikeRate: 76,
    highestBowlingSpeed: "116 km/h"
},

{
    id: 17,
    name: "Anil Kumble",
    type: "Leg Spinner",
    othertype: "Lower Order Batter",
    handtype: "Right Hand Batter / Right Arm Leg Spin",
    country: "india",
    matches: 403,
    totalRuns: 3500,
    highestScore: 110,
    catches: 115,
    fours: 280,
    sixes: 35,
    fifties: 5,
    hundreds: 1,
    wickets: 956,
    economy: 3.6,
    battingAverage: 17,
    battingStrikeRate: 66,
    highestBowlingSpeed: "126 km/h"
},

{
    id: 18,
    name: "Waqar Younis",
    type: "Fast Bowler",
    othertype: "Tailender",
    handtype: "Right Hand Batter / Right Arm Fast",
    country: "pakistan",
    matches: 349,
    totalRuns: 1600,
    highestScore: 45,
    catches: 70,
    fours: 110,
    sixes: 25,
    fifties: 0,
    hundreds: 0,
    wickets: 789,
    economy: 4.1,
    battingAverage: 11,
    battingStrikeRate: 68,
    highestBowlingSpeed: "153 km/h"
},

{
    id: 19,
    name: "Aravinda de Silva",
    type: "Batting All-Rounder",
    othertype: "Middle Order Batter",
    handtype: "Right Hand Batter",
    country: "srilanka",
    matches: 308,
    totalRuns: 10845,
    highestScore: 267,
    catches: 95,
    fours: 950,
    sixes: 85,
    fifties: 62,
    hundreds: 20,
    wickets: 106,
    economy: 4.7,
    battingAverage: 41,
    battingStrikeRate: 81,
    highestBowlingSpeed: "124 km/h"
},

{
    id: 20,
    name: "Saqlain Mushtaq",
    type: "Off Spinner",
    othertype: "Lower Order Batter",
    handtype: "Right Hand Batter / Right Arm Off Spin",
    country: "pakistan",
    matches: 218,
    totalRuns: 1200,
    highestScore: 38,
    catches: 65,
    fours: 85,
    sixes: 10,
    fifties: 0,
    hundreds: 0,
    wickets: 496,
    economy: 4.0,
    battingAverage: 10,
    battingStrikeRate: 58,
    highestBowlingSpeed: "118 km/h"
},
{
    id: 21,
    name: "Steve Waugh",
    type: "All-Rounder",
    othertype: "Middle Order Batter",
    handtype: "Right Hand Batter / Right Arm Medium",
    country: "australia",
    matches: 493,
    totalRuns: 18496,
    highestScore: 200,
    catches: 168,
    fours: 1650,
    sixes: 95,
    fifties: 102,
    hundreds: 35,
    wickets: 195,
    economy: 4.3,
    battingAverage: 46,
    battingStrikeRate: 76,
    highestBowlingSpeed: "128 km/h"
},

{
    id: 22,
    name: "Grant Flower",
    type: "Opening Batter",
    othertype: "Part Time Spinner",
    handtype: "Left Hand Batter",
    country: "zimbabwe",
    matches: 288,
    totalRuns: 9000,
    highestScore: 201,
    catches: 90,
    fours: 780,
    sixes: 55,
    fifties: 58,
    hundreds: 12,
    wickets: 25,
    economy: 4.9,
    battingAverage: 34,
    battingStrikeRate: 72,
    highestBowlingSpeed: "112 km/h"
},

{
    id: 23,
    name: "Adam Gilchrist",
    type: "Wicket-Keeper Batter",
    othertype: "captain",
    handtype: "Left Hand Batter",
    country: "australia",
    matches: 396,
    totalRuns: 15461,
    highestScore: 204,
    catches: 796,
    fours: 1600,
    sixes: 262,
    fifties: 83,
    hundreds: 33,
    wickets: 0,
    economy: 0,
    battingAverage: 39,
    battingStrikeRate: 96,
    highestBowlingSpeed: "0 km/h"
},

{
    id: 24,
    name: "Glenn McGrath",
    type: "Fast Bowler",
    othertype: "Tailender",
    handtype: "Left Hand Batter / Right Arm Fast",
    country: "australia",
    matches: 376,
    totalRuns: 900,
    highestScore: 61,
    catches: 110,
    fours: 70,
    sixes: 6,
    fifties: 1,
    hundreds: 0,
    wickets: 949,
    economy: 3.5,
    battingAverage: 8,
    battingStrikeRate: 50,
    highestBowlingSpeed: "145 km/h"
},

{
    id: 25,
    name: "Chaminda Vaas",
    type: "Fast Bowler",
    othertype: "Lower Order Batter",
    handtype: "Left Hand Batter / Left Arm Fast",
    country: "srilanka",
    matches: 439,
    totalRuns: 3000,
    highestScore: 111,
    catches: 125,
    fours: 250,
    sixes: 20,
    fifties: 3,
    hundreds: 1,
    wickets: 761,
    economy: 4.0,
    battingAverage: 15,
    battingStrikeRate: 67,
    highestBowlingSpeed: "140 km/h"
},

{
    id: 26,
    name: "Sanath Jayasuriya",
    type: "Batting All-Rounder",
    othertype: "Opening Batter",
    handtype: "Left Hand Batter / Left Arm Spin",
    country: "srilanka",
    matches: 586,
    totalRuns: 21032,
    highestScore: 340,
    catches: 155,
    fours: 2480,
    sixes: 352,
    fifties: 110,
    hundreds: 42,
    wickets: 440,
    economy: 4.8,
    battingAverage: 40,
    battingStrikeRate: 91,
    highestBowlingSpeed: "132 km/h"
},

{
    id: 27,
    name: "Michael Bevan",
    type: "Middle Order Batter",
    othertype: "Finisher",
    handtype: "Left Hand Batter",
    country: "australia",
    matches: 287,
    totalRuns: 8760,
    highestScore: 185,
    catches: 95,
    fours: 700,
    sixes: 45,
    fifties: 56,
    hundreds: 10,
    wickets: 36,
    economy: 4.7,
    battingAverage: 53,
    battingStrikeRate: 74,
    highestBowlingSpeed: "118 km/h"
},

{
    id: 28,
    name: "Sourav Ganguly",
    type: "Opening Batter",
    othertype: "captain",
    handtype: "Left Hand Batter",
    country: "india",
    matches: 421,
    totalRuns: 18433,
    highestScore: 239,
    catches: 150,
    fours: 1900,
    sixes: 247,
    fifties: 107,
    hundreds: 38,
    wickets: 132,
    economy: 5.1,
    battingAverage: 42,
    battingStrikeRate: 76,
    highestBowlingSpeed: "126 km/h"
},

{
    id: 29,
    name: "Muttiah Muralitharan",
    type: "Off Spinner",
    othertype: "Tailender",
    handtype: "Right Hand Batter / Right Arm Off Spin",
    country: "srilanka",
    matches: 495,
    totalRuns: 2000,
    highestScore: 67,
    catches: 115,
    fours: 140,
    sixes: 18,
    fifties: 0,
    hundreds: 0,
    wickets: 1347,
    economy: 3.9,
    battingAverage: 11,
    battingStrikeRate: 62,
    highestBowlingSpeed: "116 km/h"
},

{
    id: 30,
    name: "Paul Collingwood",
    type: "All-Rounder",
    othertype: "Middle Order Batter",
    handtype: "Right Hand Batter / Right Arm Medium",
    country: "england",
    matches: 301,
    totalRuns: 9150,
    highestScore: 206,
    catches: 140,
    fours: 790,
    sixes: 85,
    fifties: 49,
    hundreds: 10,
    wickets: 111,
    economy: 4.9,
    battingAverage: 36,
    battingStrikeRate: 79,
    highestBowlingSpeed: "124 km/h"
},

{
    id: 31,
    name: "Ricky Ponting",
    type: "Top Order Batter",
    othertype: "captain",
    handtype: "Right Hand Batter",
    country: "australia",
    matches: 560,
    totalRuns: 27483,
    highestScore: 257,
    catches: 364,
    fours: 2781,
    sixes: 246,
    fifties: 146,
    hundreds: 71,
    wickets: 8,
    economy: 5.2,
    battingAverage: 46,
    battingStrikeRate: 80,
    highestBowlingSpeed: "118 km/h"
},

{
    id: 32,
    name: "Chris Cairns",
    type: "All-Rounder",
    othertype: "Middle Order Batter",
    handtype: "Right Hand Batter / Right Arm Fast",
    country: "newzealand",
    matches: 332,
    totalRuns: 8273,
    highestScore: 158,
    catches: 120,
    fours: 700,
    sixes: 145,
    fifties: 43,
    hundreds: 7,
    wickets: 419,
    economy: 4.7,
    battingAverage: 33,
    battingStrikeRate: 86,
    highestBowlingSpeed: "143 km/h"
},

{
    id: 33,
    name: "Harbhajan Singh",
    type: "Off Spinner",
    othertype: "Lower Order Batter",
    handtype: "Right Hand Batter / Right Arm Off Spin",
    country: "india",
    matches: 367,
    totalRuns: 3500,
    highestScore: 115,
    catches: 105,
    fours: 260,
    sixes: 42,
    fifties: 9,
    hundreds: 2,
    wickets: 711,
    economy: 4.3,
    battingAverage: 18,
    battingStrikeRate: 74,
    highestBowlingSpeed: "122 km/h"
},

{
    id: 34,
    name: "Rahul Dravid",
    type: "Wicket-Keeper Batter",
    othertype: "captain",
    handtype: "Right Hand Batter",
    country: "india",
    matches: 509,
    totalRuns: 24208,
    highestScore: 270,
    catches: 405,
    fours: 2600,
    sixes: 66,
    fifties: 146,
    hundreds: 48,
    wickets: 1,
    economy: 5.4,
    battingAverage: 45,
    battingStrikeRate: 71,
    highestBowlingSpeed: "110 km/h"
},

{
    id: 35,
    name: "Shahid Afridi",
    type: "All-Rounder",
    othertype: "captain",
    handtype: "Right Hand Batter / Right Arm Leg Spin",
    country: "pakistan",
    matches: 524,
    totalRuns: 11196,
    highestScore: 156,
    catches: 139,
    fours: 1050,
    sixes: 476,
    fifties: 51,
    hundreds: 11,
    wickets: 541,
    economy: 4.8,
    battingAverage: 24,
    battingStrikeRate: 117,
    highestBowlingSpeed: "134 km/h"
},

{
    id: 36,
    name: "Herschelle Gibbs",
    type: "Opening Batter",
    othertype: "Part Time Bowler",
    handtype: "Right Hand Batter",
    country: "southafrica",
    matches: 361,
    totalRuns: 14000,
    highestScore: 228,
    catches: 160,
    fours: 1550,
    sixes: 190,
    fifties: 75,
    hundreds: 24,
    wickets: 18,
    economy: 5.0,
    battingAverage: 41,
    battingStrikeRate: 84,
    highestBowlingSpeed: "121 km/h"
},

{
    id: 37,
    name: "Jacques Kallis",
    type: "Batting All-Rounder",
    othertype: "Top Order Batter",
    handtype: "Right Hand Batter / Right Arm Fast Medium",
    country: "southafrica",
    matches: 519,
    totalRuns: 25534,
    highestScore: 224,
    catches: 338,
    fours: 2450,
    sixes: 254,
    fifties: 149,
    hundreds: 62,
    wickets: 577,
    economy: 4.3,
    battingAverage: 49,
    battingStrikeRate: 73,
    highestBowlingSpeed: "140 km/h"
},

{
    id: 38,
    name: "Daniel Vettori",
    type: "Spin Bowling All-Rounder",
    othertype: "Lower Order Batter",
    handtype: "Left Hand Batter / Left Arm Spin",
    country: "newzealand",
    matches: 442,
    totalRuns: 6989,
    highestScore: 140,
    catches: 150,
    fours: 540,
    sixes: 58,
    fifties: 24,
    hundreds: 6,
    wickets: 705,
    economy: 4.1,
    battingAverage: 30,
    battingStrikeRate: 76,
    highestBowlingSpeed: "118 km/h"
},

{
    id: 39,
    name: "Mashrafe Mortaza",
    type: "Fast Bowler",
    othertype: "Lower Order Batter",
    handtype: "Right Hand Batter / Right Arm Fast",
    country: "bangladesh",
    matches: 295,
    totalRuns: 2200,
    highestScore: 44,
    catches: 78,
    fours: 160,
    sixes: 32,
    fifties: 0,
    hundreds: 0,
    wickets: 390,
    economy: 4.9,
    battingAverage: 14,
    battingStrikeRate: 83,
    highestBowlingSpeed: "145 km/h"
},

{
    id: 40,
    name: "Shaun Pollock",
    type: "Bowling All-Rounder",
    othertype: "Lower Order Batter",
    handtype: "Right Hand Batter / Right Arm Fast Medium",
    country: "southafrica",
    matches: 423,
    totalRuns: 7386,
    highestScore: 111,
    catches: 170,
    fours: 620,
    sixes: 65,
    fifties: 26,
    hundreds: 2,
    wickets: 829,
    economy: 3.7,
    battingAverage: 31,
    battingStrikeRate: 76,
    highestBowlingSpeed: "138 km/h"
},

{
    id: 41,
    name: "Brendon McCullum",
    type: "Wicket-Keeper Batter",
    othertype: "Opening Batter",
    handtype: "Right Hand Batter",
    country: "newzealand",
    matches: 432,
    totalRuns: 14676,
    highestScore: 302,
    catches: 430,
    fours: 1450,
    sixes: 398,
    fifties: 76,
    hundreds: 19,
    wickets: 0,
    economy: 0,
    battingAverage: 38,
    battingStrikeRate: 96,
    highestBowlingSpeed: "0 km/h"
},

{
    id: 42,
    name: "Yuvraj Singh",
    type: "Batting All-Rounder",
    othertype: "Middle Order Batter",
    handtype: "Left Hand Batter / Slow Left Arm",
    country: "india",
    matches: 402,
    totalRuns: 11778,
    highestScore: 169,
    catches: 154,
    fours: 1030,
    sixes: 251,
    fifties: 71,
    hundreds: 17,
    wickets: 148,
    economy: 5.1,
    battingAverage: 36,
    battingStrikeRate: 88,
    highestBowlingSpeed: "129 km/h"
},

{
    id: 43,
    name: "Virender Sehwag",
    type: "Opening Batter",
    othertype: "Part Time Off Spinner",
    handtype: "Right Hand Batter / Right Arm Off Spin",
    country: "india",
    matches: 374,
    totalRuns: 17253,
    highestScore: 319,
    catches: 115,
    fours: 2200,
    sixes: 243,
    fifties: 75,
    hundreds: 38,
    wickets: 136,
    economy: 4.8,
    battingAverage: 40,
    battingStrikeRate: 95,
    highestBowlingSpeed: "122 km/h"
},

{
    id: 44,
    name: "Zaheer Khan",
    type: "Fast Bowler",
    othertype: "Lower Order Batter",
    handtype: "Left Hand Batter / Left Arm Fast",
    country: "india",
    matches: 309,
    totalRuns: 1800,
    highestScore: 75,
    catches: 88,
    fours: 140,
    sixes: 18,
    fifties: 1,
    hundreds: 0,
    wickets: 610,
    economy: 4.5,
    battingAverage: 13,
    battingStrikeRate: 69,
    highestBowlingSpeed: "145 km/h"
},

{
    id: 45,
    name: "Makhaya Ntini",
    type: "Fast Bowler",
    othertype: "Tailender",
    handtype: "Right Hand Batter / Right Arm Fast",
    country: "southafrica",
    matches: 283,
    totalRuns: 900,
    highestScore: 32,
    catches: 68,
    fours: 75,
    sixes: 5,
    fifties: 0,
    hundreds: 0,
    wickets: 661,
    economy: 4.1,
    battingAverage: 9,
    battingStrikeRate: 54,
    highestBowlingSpeed: "148 km/h"
},

{
    id: 46,
    name: "Kumar Sangakkara",
    type: "Wicket-Keeper Batter",
    othertype: "captain",
    handtype: "Left Hand Batter",
    country: "srilanka",
    matches: 594,
    totalRuns: 28016,
    highestScore: 319,
    catches: 678,
    fours: 3015,
    sixes: 159,
    fifties: 153,
    hundreds: 63,
    wickets: 0,
    economy: 0,
    battingAverage: 46,
    battingStrikeRate: 78,
    highestBowlingSpeed: "0 km/h"
},

{
    id: 47,
    name: "Mahela Jayawardene",
    type: "Top Order Batter",
    othertype: "Middle Order Batter",
    handtype: "Right Hand Batter",
    country: "srilanka",
    matches: 652,
    totalRuns: 25957,
    highestScore: 374,
    catches: 440,
    fours: 2490,
    sixes: 170,
    fifties: 136,
    hundreds: 54,
    wickets: 8,
    economy: 5.3,
    battingAverage: 42,
    battingStrikeRate: 74,
    highestBowlingSpeed: "112 km/h"
},

{
    id: 48,
    name: "Shoaib Malik",
    type: "Batting All-Rounder",
    othertype: "Middle Order Batter",
    handtype: "Right Hand Batter / Right Arm Off Spin",
    country: "pakistan",
    matches: 446,
    totalRuns: 11767,
    highestScore: 245,
    catches: 140,
    fours: 1010,
    sixes: 140,
    fifties: 64,
    hundreds: 12,
    wickets: 218,
    economy: 4.6,
    battingAverage: 36,
    battingStrikeRate: 82,
    highestBowlingSpeed: "126 km/h"
},

{
    id: 49,
    name: "MS Dhoni",
    type: "Wicket-Keeper Batter",
    othertype: "captain",
    handtype: "Right Hand Batter",
    country: "india",
    matches: 538,
    totalRuns: 17092,
    highestScore: 224,
    catches: 634,
    fours: 1485,
    sixes: 359,
    fifties: 108,
    hundreds: 16,
    wickets: 1,
    economy: 8.0,
    battingAverage: 44,
    battingStrikeRate: 87,
    highestBowlingSpeed: "122 km/h"
},

{
    id: 50,
    name: "Abdul Razzaq",
    type: "All-Rounder",
    othertype: "Lower Order Batter",
    handtype: "Right Hand Batter / Right Arm Fast Medium",
    country: "pakistan",
    matches: 343,
    totalRuns: 5080,
    highestScore: 112,
    catches: 92,
    fours: 420,
    sixes: 95,
    fifties: 23,
    hundreds: 3,
    wickets: 389,
    economy: 4.8,
    battingAverage: 29,
    battingStrikeRate: 92,
    highestBowlingSpeed: "138 km/h"
},

{
    id: 51,
    name: "Lasith Malinga",
    type: "Fast Bowler",
    othertype: "Tailender",
    handtype: "Right Hand Batter / Right Arm Fast",
    country: "srilanka",
    matches: 340,
    totalRuns: 900,
    highestScore: 56,
    catches: 85,
    fours: 72,
    sixes: 12,
    fifties: 0,
    hundreds: 0,
    wickets: 546,
    economy: 5.0,
    battingAverage: 8,
    battingStrikeRate: 61,
    highestBowlingSpeed: "155 km/h"
},

{
    id: 52,
    name: "Tillakaratne Dilshan",
    type: "Batting All-Rounder",
    othertype: "Opening Batter",
    handtype: "Right Hand Batter / Right Arm Off Spin",
    country: "srilanka",
    matches: 497,
    totalRuns: 17671,
    highestScore: 161,
    catches: 180,
    fours: 1650,
    sixes: 150,
    fifties: 97,
    hundreds: 22,
    wickets: 150,
    economy: 4.9,
    battingAverage: 39,
    battingStrikeRate: 86,
    highestBowlingSpeed: "125 km/h"
},

{
    id: 53,
    name: "Shoaib Akhtar",
    type: "Fast Bowler",
    othertype: "Tailender",
    handtype: "Right Hand Batter / Right Arm Fast",
    country: "pakistan",
    matches: 224,
    totalRuns: 800,
    highestScore: 45,
    catches: 60,
    fours: 50,
    sixes: 10,
    fifties: 0,
    hundreds: 0,
    wickets: 444,
    economy: 4.6,
    battingAverage: 7,
    battingStrikeRate: 58,
    highestBowlingSpeed: "161 km/h"
},

{
    id: 54,
    name: "Hashim Amla",
    type: "Top Order Batter",
    othertype: "Opening Batter",
    handtype: "Right Hand Batter",
    country: "southafrica",
    matches: 349,
    totalRuns: 18672,
    highestScore: 311,
    catches: 140,
    fours: 1900,
    sixes: 110,
    fifties: 88,
    hundreds: 55,
    wickets: 0,
    economy: 0,
    battingAverage: 46,
    battingStrikeRate: 88,
    highestBowlingSpeed: "0 km/h"
},

{
    id: 55,
    name: "Ross Taylor",
    type: "Middle Order Batter",
    othertype: "Finisher",
    handtype: "Right Hand Batter",
    country: "newzealand",
    matches: 450,
    totalRuns: 18900,
    highestScore: 181,
    catches: 160,
    fours: 1700,
    sixes: 140,
    fifties: 92,
    hundreds: 40,
    wickets: 5,
    economy: 5.0,
    battingAverage: 42,
    battingStrikeRate: 83,
    highestBowlingSpeed: "118 km/h"
},

{
    id: 56,
    name: "James Anderson",
    type: "Fast Bowler",
    othertype: "Tailender",
    handtype: "Left Hand Batter / Right Arm Fast",
    country: "england",
    matches: 400,
    totalRuns: 1200,
    highestScore: 81,
    catches: 120,
    fours: 95,
    sixes: 8,
    fifties: 1,
    hundreds: 0,
    wickets: 980,
    economy: 2.9,
    battingAverage: 9,
    battingStrikeRate: 52,
    highestBowlingSpeed: "141 km/h"
},

{
    id: 57,
    name: "Chris Gayle",
    type: "Batting All-Rounder",
    othertype: "Opening Batter",
    handtype: "Left Hand Batter / Right Arm Off Spin",
    country: "westindies",
    matches: 483,
    totalRuns: 19593,
    highestScore: 333,
    catches: 160,
    fours: 2100,
    sixes: 553,
    fifties: 102,
    hundreds: 42,
    wickets: 165,
    economy: 5.2,
    battingAverage: 42,
    battingStrikeRate: 87,
    highestBowlingSpeed: "130 km/h"
},

{
    id: 58,
    name: "Ajit Agarkar",
    type: "Bowling All-Rounder",
    othertype: "Lower Order Batter",
    handtype: "Right Hand Batter / Right Arm Fast",
    country: "india",
    matches: 221,
    totalRuns: 3000,
    highestScore: 95,
    catches: 75,
    fours: 240,
    sixes: 35,
    fifties: 4,
    hundreds: 0,
    wickets: 288,
    economy: 4.7,
    battingAverage: 20,
    battingStrikeRate: 78,
    highestBowlingSpeed: "140 km/h"
},

{
    id: 59,
    name: "Virat Kohli",
    type: "Top Order Batter",
    othertype: "captain",
    handtype: "Right Hand Batter",
    country: "india",
    matches: 550,
    totalRuns: 27400,
    highestScore: 183,
    catches: 270,
    fours: 2600,
    sixes: 300,
    fifties: 140,
    hundreds: 82,
    wickets: 8,
    economy: 5.0,
    battingAverage: 58,
    battingStrikeRate: 93,
    highestBowlingSpeed: "120 km/h"
},

{
    id: 60,
    name: "AB de Villiers",
    type: "Wicket-Keeper Batter",
    othertype: "captain",
    handtype: "Right Hand Batter",
    country: "southafrica",
    matches: 420,
    totalRuns: 21000,
    highestScore: 176,
    catches: 420,
    fours: 1800,
    sixes: 328,
    fifties: 100,
    hundreds: 47,
    wickets: 7,
    economy: 5.1,
    battingAverage: 50,
    battingStrikeRate: 101,
    highestBowlingSpeed: "120 km/h"
},
{
    id: 61,
    name: "Kevin Pietersen",
    type: "Top Order Batter",
    othertype: "Middle Order Batter",
    handtype: "Right Hand Batter / Right Arm Off Spin",
    country: "england",
    matches: 277,
    totalRuns: 13700,
    highestScore: 227,
    catches: 120,
    fours: 1300,
    sixes: 210,
    fifties: 63,
    hundreds: 32,
    wickets: 0,
    economy: 0,
    battingAverage: 47,
    battingStrikeRate: 95,
    highestBowlingSpeed: "0 km/h"
},

{
    id: 62,
    name: "Mohammad Yousuf",
    type: "Top Order Batter",
    othertype: "Middle Order Batter",
    handtype: "Right Hand Batter",
    country: "pakistan",
    matches: 381,
    totalRuns: 17100,
    highestScore: 223,
    catches: 110,
    fours: 1600,
    sixes: 120,
    fifties: 90,
    hundreds: 39,
    wickets: 3,
    economy: 5.3,
    battingAverage: 52,
    battingStrikeRate: 80,
    highestBowlingSpeed: "115 km/h"
},

{
    id: 63,
    name: "Rohit Sharma",
    type: "Opening Batter",
    othertype: "captain",
    handtype: "Right Hand Batter",
    country: "india",
    matches: 450,
    totalRuns: 18400,
    highestScore: 264,
    catches: 140,
    fours: 1800,
    sixes: 520,
    fifties: 95,
    hundreds: 49,
    wickets: 8,
    economy: 5.4,
    battingAverage: 48,
    battingStrikeRate: 91,
    highestBowlingSpeed: "125 km/h"
},

{
    id: 64,
    name: "Shivnarine Chanderpaul",
    type: "Middle Order Batter",
    othertype: "Part Time Spinner",
    handtype: "Left Hand Batter",
    country: "westindies",
    matches: 454,
    totalRuns: 20900,
    highestScore: 203,
    catches: 180,
    fours: 1750,
    sixes: 90,
    fifties: 110,
    hundreds: 41,
    wickets: 9,
    economy: 5.0,
    battingAverage: 41,
    battingStrikeRate: 70,
    highestBowlingSpeed: "110 km/h"
},

{
    id: 65,
    name: "Brett Lee",
    type: "Fast Bowler",
    othertype: "Lower Order Batter",
    handtype: "Right Hand Batter / Right Arm Fast",
    country: "australia",
    matches: 380,
    totalRuns: 1500,
    highestScore: 59,
    catches: 110,
    fours: 110,
    sixes: 25,
    fifties: 1,
    hundreds: 0,
    wickets: 718,
    economy: 4.7,
    battingAverage: 16,
    battingStrikeRate: 85,
    highestBowlingSpeed: "161 km/h"
},

{
    id: 66,
    name: "Hansie Cronje",
    type: "All-Rounder",
    othertype: "Middle Order Batter",
    handtype: "Right Hand Batter / Right Arm Medium",
    country: "southafrica",
    matches: 308,
    totalRuns: 7300,
    highestScore: 112,
    catches: 120,
    fours: 650,
    sixes: 80,
    fifties: 35,
    hundreds: 8,
    wickets: 120,
    economy: 4.9,
    battingAverage: 38,
    battingStrikeRate: 79,
    highestBowlingSpeed: "128 km/h"
},

{
    id: 67,
    name: "Ravindra Jadeja",
    type: "Bowling All-Rounder",
    othertype: "Left Arm Spinner",
    handtype: "Left Hand Batter",
    country: "india",
    matches: 350,
    totalRuns: 8500,
    highestScore: 175,
    catches: 180,
    fours: 700,
    sixes: 180,
    fifties: 45,
    hundreds: 3,
    wickets: 520,
    economy: 4.6,
    battingAverage: 34,
    battingStrikeRate: 87,
    highestBowlingSpeed: "135 km/h"
}
    {
    id: 68,
    name: "Alec Stewart",
    type: "Wicket-Keeper Batter",
    othertype: "captain",
    handtype: "Right Hand Batter",
    country: "england",
    matches: 170,
    totalRuns: 4677,
    highestScore: 116,
    catches: 174,
    fours: 460,
    sixes: 20,
    fifties: 28,
    hundreds: 4,
    wickets: 0,
    economy: 0,
    battingAverage: 31,
    battingStrikeRate: 72,
    highestBowlingSpeed: "0 km/h"
},
 
{
    id: 69,
    name: "Henry Olonga",
    type: "Fast Bowler",
    othertype: "Tailender",
    handtype: "Right Hand Batter / Right Arm Fast",
    country: "zimbabwe",
    matches: 50,
    totalRuns: 90,
    highestScore: 16,
    catches: 10,
    fours: 8,
    sixes: 2,
    fifties: 0,
    hundreds: 0,
    wickets: 58,
    economy: 5.5,
    battingAverage: 5,
    battingStrikeRate: 60,
    highestBowlingSpeed: "145 km/h"
},
 
{
    id: 70,
    name: "Dale Steyn",
    type: "Fast Bowler",
    othertype: "Tailender",
    handtype: "Right Hand Batter / Right Arm Fast",
    country: "southafrica",
    matches: 125,
    totalRuns: 305,
    highestScore: 60,
    catches: 35,
    fours: 25,
    sixes: 6,
    fifties: 1,
    hundreds: 0,
    wickets: 196,
    economy: 4.9,
    battingAverage: 8,
    battingStrikeRate: 78,
    highestBowlingSpeed: "155 km/h"
},
 
{
    id: 71,
    name: "Quinton de Kock",
    type: "Wicket-Keeper Batter",
    othertype: "Opening Batter",
    handtype: "Left Hand Batter",
    country: "southafrica",
    matches: 155,
    totalRuns: 6770,
    highestScore: 178,
    catches: 230,
    fours: 700,
    sixes: 120,
    fifties: 30,
    hundreds: 21,
    wickets: 0,
    economy: 0,
    battingAverage: 45,
    battingStrikeRate: 97,
    highestBowlingSpeed: "0 km/h"
},
 
{
    id: 72,
    name: "Andy Flower",
    type: "Wicket-Keeper Batter",
    othertype: "captain",
    handtype: "Left Hand Batter",
    country: "zimbabwe",
    matches: 213,
    totalRuns: 6786,
    highestScore: 145,
    catches: 141,
    fours: 600,
    sixes: 30,
    fifties: 55,
    hundreds: 4,
    wickets: 0,
    economy: 0,
    battingAverage: 35,
    battingStrikeRate: 74,
    highestBowlingSpeed: "0 km/h"
},
 
{
    id: 73,
    name: "Gordon Greenidge",
    type: "Opening Batter",
    othertype: "Top Order Batter",
    handtype: "Right Hand Batter",
    country: "westindies",
    matches: 128,
    totalRuns: 5134,
    highestScore: 133,
    catches: 45,
    fours: 480,
    sixes: 35,
    fifties: 31,
    hundreds: 11,
    wickets: 0,
    economy: 0,
    battingAverage: 45,
    battingStrikeRate: 65,
    highestBowlingSpeed: "0 km/h"
},
 
{
    id: 74,
    name: "Sean Williams",
    type: "Batting All-Rounder",
    othertype: "Middle Order Batter",
    handtype: "Left Hand Batter / Slow Left Arm",
    country: "zimbabwe",
    matches: 156,
    totalRuns: 4955,
    highestScore: 129,
    catches: 70,
    fours: 420,
    sixes: 60,
    fifties: 32,
    hundreds: 5,
    wickets: 67,
    economy: 4.8,
    battingAverage: 38,
    battingStrikeRate: 78,
    highestBowlingSpeed: "92 km/h"
},
 
{
    id: 75,
    name: "Graeme Smith",
    type: "Opening Batter",
    othertype: "captain",
    handtype: "Left Hand Batter / Right Arm Off Spin",
    country: "southafrica",
    matches: 197,
    totalRuns: 6989,
    highestScore: 141,
    catches: 90,
    fours: 720,
    sixes: 65,
    fifties: 47,
    hundreds: 10,
    wickets: 18,
    economy: 5.1,
    battingAverage: 38,
    battingStrikeRate: 80,
    highestBowlingSpeed: "112 km/h"
},
 
{
    id: 76,
    name: "Mustafizur Rahman",
    type: "Fast Bowler",
    othertype: "Tailender",
    handtype: "Left Hand Batter / Left Arm Fast Medium",
    country: "bangladesh",
    matches: 109,
    totalRuns: 130,
    highestScore: 18,
    catches: 25,
    fours: 10,
    sixes: 2,
    fifties: 0,
    hundreds: 0,
    wickets: 178,
    economy: 5.2,
    battingAverage: 5,
    battingStrikeRate: 60,
    highestBowlingSpeed: "140 km/h"
},
 
{
    id: 77,
    name: "Elton Chigumbura",
    type: "Bowling All-Rounder",
    othertype: "captain",
    handtype: "Right Hand Batter / Right Arm Medium Fast",
    country: "zimbabwe",
    matches: 213,
    totalRuns: 4112,
    highestScore: 117,
    catches: 75,
    fours: 320,
    sixes: 90,
    fifties: 17,
    hundreds: 2,
    wickets: 105,
    economy: 5.4,
    battingAverage: 24,
    battingStrikeRate: 82,
    highestBowlingSpeed: "130 km/h"
},
 
{
    id: 78,
    name: "Clive Lloyd",
    type: "Middle Order Batter",
    othertype: "captain",
    handtype: "Left Hand Batter",
    country: "westindies",
    matches: 87,
    totalRuns: 1977,
    highestScore: 102,
    catches: 39,
    fours: 180,
    sixes: 25,
    fifties: 11,
    hundreds: 1,
    wickets: 8,
    economy: 4.3,
    battingAverage: 39,
    battingStrikeRate: 81,
    highestBowlingSpeed: "118 km/h"
},
 
{
    id: 79,
    name: "Ian Botham",
    type: "Bowling All-Rounder",
    othertype: "Lower Order Batter",
    handtype: "Right Hand Batter / Right Arm Fast Medium",
    country: "england",
    matches: 116,
    totalRuns: 2113,
    highestScore: 79,
    catches: 36,
    fours: 200,
    sixes: 40,
    fifties: 9,
    hundreds: 0,
    wickets: 145,
    economy: 3.9,
    battingAverage: 24,
    battingStrikeRate: 79,
    highestBowlingSpeed: "135 km/h"
},
 
{
    id: 80,
    name: "Upul Tharanga",
    type: "Opening Batter",
    othertype: "captain",
    handtype: "Left Hand Batter",
    country: "srilanka",
    matches: 235,
    totalRuns: 6951,
    highestScore: 174,
    catches: 60,
    fours: 720,
    sixes: 55,
    fifties: 37,
    hundreds: 15,
    wickets: 0,
    economy: 0,
    battingAverage: 33,
    battingStrikeRate: 77,
    highestBowlingSpeed: "0 km/h"
},
 
{
    id: 81,
    name: "Tatenda Taibu",
    type: "Wicket-Keeper Batter",
    othertype: "captain",
    handtype: "Right Hand Batter",
    country: "zimbabwe",
    matches: 150,
    totalRuns: 3393,
    highestScore: 107,
    catches: 120,
    fours: 300,
    sixes: 15,
    fifties: 23,
    hundreds: 1,
    wickets: 0,
    economy: 0,
    battingAverage: 28,
    battingStrikeRate: 67,
    highestBowlingSpeed: "0 km/h"
},
 
{
    id: 82,
    name: "Graham Gooch",
    type: "Opening Batter",
    othertype: "captain",
    handtype: "Right Hand Batter / Right Arm Medium",
    country: "england",
    matches: 125,
    totalRuns: 4290,
    highestScore: 142,
    catches: 45,
    fours: 420,
    sixes: 20,
    fifties: 23,
    hundreds: 8,
    wickets: 36,
    economy: 4.6,
    battingAverage: 36,
    battingStrikeRate: 70,
    highestBowlingSpeed: "118 km/h"
},
 
{
    id: 83,
    name: "Neil Johnson",
    type: "Batting All-Rounder",
    othertype: "Opening Batter",
    handtype: "Left Hand Batter / Right Arm Medium",
    country: "zimbabwe",
    matches: 48,
    totalRuns: 1679,
    highestScore: 132,
    catches: 25,
    fours: 180,
    sixes: 20,
    fifties: 11,
    hundreds: 4,
    wickets: 47,
    economy: 4.7,
    battingAverage: 37,
    battingStrikeRate: 80,
    highestBowlingSpeed: "128 km/h"
},
 
{
    id: 84,
    name: "Brendan Taylor",
    type: "Wicket-Keeper Batter",
    othertype: "captain",
    handtype: "Right Hand Batter",
    country: "zimbabwe",
    matches: 205,
    totalRuns: 6677,
    highestScore: 145,
    catches: 150,
    fours: 600,
    sixes: 60,
    fifties: 39,
    hundreds: 11,
    wickets: 9,
    economy: 5.8,
    battingAverage: 35,
    battingStrikeRate: 76,
    highestBowlingSpeed: "108 km/h"
},
 
{
    id: 85,
    name: "Kane Williamson",
    type: "Top Order Batter",
    othertype: "captain",
    handtype: "Right Hand Batter / Right Arm Off Spin",
    country: "newzealand",
    matches: 165,
    totalRuns: 6554,
    highestScore: 148,
    catches: 75,
    fours: 600,
    sixes: 45,
    fifties: 42,
    hundreds: 13,
    wickets: 37,
    economy: 5.3,
    battingAverage: 47,
    battingStrikeRate: 81,
    highestBowlingSpeed: "112 km/h"
},
 
{
    id: 86,
    name: "Angelo Mathews",
    type: "Batting All-Rounder",
    othertype: "captain",
    handtype: "Right Hand Batter / Right Arm Medium",
    country: "srilanka",
    matches: 226,
    totalRuns: 5835,
    highestScore: 139,
    catches: 70,
    fours: 440,
    sixes: 70,
    fifties: 39,
    hundreds: 3,
    wickets: 120,
    economy: 5,
    battingAverage: 41,
    battingStrikeRate: 82,
    highestBowlingSpeed: "132 km/h"
},
 
{
    id: 87,
    name: "Mohammad Rafique",
    type: "Spin Bowling All-Rounder",
    othertype: "Lower Order Batter",
    handtype: "Left Hand Batter / Slow Left Arm",
    country: "bangladesh",
    matches: 125,
    totalRuns: 1191,
    highestScore: 77,
    catches: 30,
    fours: 110,
    sixes: 25,
    fifties: 3,
    hundreds: 0,
    wickets: 119,
    economy: 4.4,
    battingAverage: 13,
    battingStrikeRate: 82,
    highestBowlingSpeed: "85 km/h"
},
 
{
    id: 88,
    name: "Michael Holding",
    type: "Fast Bowler",
    othertype: "Tailender",
    handtype: "Right Hand Batter / Right Arm Fast",
    country: "westindies",
    matches: 102,
    totalRuns: 282,
    highestScore: 64,
    catches: 30,
    fours: 22,
    sixes: 5,
    fifties: 1,
    hundreds: 0,
    wickets: 142,
    economy: 3.3,
    battingAverage: 9,
    battingStrikeRate: 70,
    highestBowlingSpeed: "155 km/h"
},
 
{
    id: 89,
    name: "Alistair Campbell",
    type: "Top Order Batter",
    othertype: "captain",
    handtype: "Left Hand Batter",
    country: "zimbabwe",
    matches: 188,
    totalRuns: 5185,
    highestScore: 131,
    catches: 80,
    fours: 460,
    sixes: 30,
    fifties: 30,
    hundreds: 7,
    wickets: 4,
    economy: 5.4,
    battingAverage: 30,
    battingStrikeRate: 67,
    highestBowlingSpeed: "108 km/h"
},
 
{
    id: 90,
    name: "Heath Streak",
    type: "Bowling All-Rounder",
    othertype: "captain",
    handtype: "Right Hand Batter / Right Arm Fast Medium",
    country: "zimbabwe",
    matches: 189,
    totalRuns: 2943,
    highestScore: 79,
    catches: 50,
    fours: 240,
    sixes: 35,
    fifties: 13,
    hundreds: 0,
    wickets: 239,
    economy: 4.5,
    battingAverage: 28,
    battingStrikeRate: 75,
    highestBowlingSpeed: "140 km/h"
},
 
{
    id: 91,
    name: "Mahmudullah",
    type: "Batting All-Rounder",
    othertype: "Finisher",
    handtype: "Right Hand Batter / Right Arm Off Spin",
    country: "bangladesh",
    matches: 232,
    totalRuns: 5689,
    highestScore: 128,
    catches: 80,
    fours: 420,
    sixes: 90,
    fifties: 33,
    hundreds: 4,
    wickets: 84,
    economy: 5.2,
    battingAverage: 36,
    battingStrikeRate: 77,
    highestBowlingSpeed: "112 km/h"
},
 
{
    id: 92,
    name: "Mitchell Starc",
    type: "Fast Bowler",
    othertype: "Lower Order Batter",
    handtype: "Left Hand Batter / Left Arm Fast",
    country: "australia",
    matches: 121,
    totalRuns: 555,
    highestScore: 52,
    catches: 35,
    fours: 45,
    sixes: 15,
    fifties: 1,
    hundreds: 0,
    wickets: 244,
    economy: 5.2,
    battingAverage: 13,
    battingStrikeRate: 90,
    highestBowlingSpeed: "160 km/h"
},
 
{
    id: 93,
    name: "Andrew Flintoff",
    type: "Bowling All-Rounder",
    othertype: "Finisher",
    handtype: "Right Hand Batter / Right Arm Fast",
    country: "england",
    matches: 141,
    totalRuns: 3394,
    highestScore: 123,
    catches: 50,
    fours: 280,
    sixes: 80,
    fifties: 18,
    hundreds: 3,
    wickets: 169,
    economy: 4.5,
    battingAverage: 32,
    battingStrikeRate: 89,
    highestBowlingSpeed: "145 km/h"
},
 
{
    id: 94,
    name: "Alastair Cook",
    type: "Opening Batter",
    othertype: "captain",
    handtype: "Left Hand Batter",
    country: "england",
    matches: 92,
    totalRuns: 3204,
    highestScore: 137,
    catches: 36,
    fours: 320,
    sixes: 15,
    fifties: 19,
    hundreds: 5,
    wickets: 0,
    economy: 0,
    battingAverage: 37,
    battingStrikeRate: 77,
    highestBowlingSpeed: "0 km/h"
},
 
{
    id: 95,
    name: "Stephen Fleming",
    type: "Top Order Batter",
    othertype: "captain",
    handtype: "Left Hand Batter",
    country: "newzealand",
    matches: 280,
    totalRuns: 8037,
    highestScore: 134,
    catches: 133,
    fours: 740,
    sixes: 40,
    fifties: 49,
    hundreds: 8,
    wickets: 1,
    economy: 5.5,
    battingAverage: 32,
    battingStrikeRate: 71,
    highestBowlingSpeed: "108 km/h"
},
 
{
    id: 96,
    name: "Mohammad Ashraful",
    type: "Middle Order Batter",
    othertype: "Part Time Leg Spinner",
    handtype: "Right Hand Batter / Right Arm Leg Spin",
    country: "bangladesh",
    matches: 177,
    totalRuns: 3468,
    highestScore: 109,
    catches: 40,
    fours: 340,
    sixes: 40,
    fifties: 20,
    hundreds: 3,
    wickets: 18,
    economy: 5.3,
    battingAverage: 22,
    battingStrikeRate: 70,
    highestBowlingSpeed: "108 km/h"
},
 
{
    id: 97,
    name: "Eoin Morgan",
    type: "Middle Order Batter",
    othertype: "captain",
    handtype: "Left Hand Batter",
    country: "england",
    matches: 248,
    totalRuns: 7701,
    highestScore: 148,
    catches: 90,
    fours: 620,
    sixes: 220,
    fifties: 47,
    hundreds: 14,
    wickets: 0,
    economy: 0,
    battingAverage: 39,
    battingStrikeRate: 91,
    highestBowlingSpeed: "0 km/h"
},
 
{
    id: 98,
    name: "Mushfiqur Rahim",
    type: "Wicket-Keeper Batter",
    othertype: "Middle Order Batter",
    handtype: "Right Hand Batter",
    country: "bangladesh",
    matches: 274,
    totalRuns: 7795,
    highestScore: 144,
    catches: 240,
    fours: 660,
    sixes: 60,
    fifties: 49,
    hundreds: 9,
    wickets: 0,
    economy: 0,
    battingAverage: 37,
    battingStrikeRate: 79,
    highestBowlingSpeed: "0 km/h"
},
 
{
    id: 99,
    name: "Arjuna Ranatunga",
    type: "Middle Order Batter",
    othertype: "captain",
    handtype: "Right Hand Batter / Right Arm Medium",
    country: "srilanka",
    matches: 269,
    totalRuns: 7456,
    highestScore: 131,
    catches: 63,
    fours: 600,
    sixes: 40,
    fifties: 49,
    hundreds: 4,
    wickets: 79,
    economy: 4.8,
    battingAverage: 35,
    battingStrikeRate: 77,
    highestBowlingSpeed: "118 km/h"
},
 
{
    id: 100,
    name: "Marvan Atapattu",
    type: "Opening Batter",
    othertype: "captain",
    handtype: "Right Hand Batter",
    country: "srilanka",
    matches: 268,
    totalRuns: 8529,
    highestScore: 132,
    catches: 80,
    fours: 760,
    sixes: 35,
    fifties: 59,
    hundreds: 11,
    wickets: 0,
    economy: 0,
    battingAverage: 37,
    battingStrikeRate: 70,
    highestBowlingSpeed: "0 km/h"
},
 
{
    id: 101,
    name: "Dwayne Bravo",
    type: "Bowling All-Rounder",
    othertype: "Finisher",
    handtype: "Right Hand Batter / Right Arm Medium Fast",
    country: "westindies",
    matches: 164,
    totalRuns: 2968,
    highestScore: 112,
    catches: 70,
    fours: 250,
    sixes: 80,
    fifties: 10,
    hundreds: 2,
    wickets: 199,
    economy: 5,
    battingAverage: 25,
    battingStrikeRate: 82,
    highestBowlingSpeed: "135 km/h"
},
 
{
    id: 102,
    name: "Allan Border",
    type: "Middle Order Batter",
    othertype: "captain",
    handtype: "Left Hand Batter / Slow Left Arm",
    country: "australia",
    matches: 273,
    totalRuns: 6524,
    highestScore: 127,
    catches: 127,
    fours: 540,
    sixes: 30,
    fifties: 39,
    hundreds: 3,
    wickets: 73,
    economy: 4.6,
    battingAverage: 30,
    battingStrikeRate: 71,
    highestBowlingSpeed: "108 km/h"
},
 
{
    id: 103,
    name: "Hamilton Masakadza",
    type: "Opening Batter",
    othertype: "Part Time Off Spinner",
    handtype: "Right Hand Batter / Right Arm Off Spin",
    country: "zimbabwe",
    matches: 209,
    totalRuns: 5658,
    highestScore: 178,
    catches: 60,
    fours: 540,
    sixes: 55,
    fifties: 30,
    hundreds: 5,
    wickets: 25,
    economy: 5.2,
    battingAverage: 27,
    battingStrikeRate: 73,
    highestBowlingSpeed: "112 km/h"
},
 
{
    id: 104,
    name: "Martin Crowe",
    type: "Middle Order Batter",
    othertype: "captain",
    handtype: "Right Hand Batter / Right Arm Medium",
    country: "newzealand",
    matches: 143,
    totalRuns: 4704,
    highestScore: 107,
    catches: 66,
    fours: 420,
    sixes: 30,
    fifties: 34,
    hundreds: 4,
    wickets: 29,
    economy: 4.7,
    battingAverage: 38,
    battingStrikeRate: 72,
    highestBowlingSpeed: "120 km/h"
},
 
{
    id: 105,
    name: "Martin Guptill",
    type: "Opening Batter",
    othertype: "Top Order Batter",
    handtype: "Right Hand Batter / Right Arm Off Spin",
    country: "newzealand",
    matches: 198,
    totalRuns: 7346,
    highestScore: 237,
    catches: 90,
    fours: 700,
    sixes: 187,
    fifties: 39,
    hundreds: 18,
    wickets: 6,
    economy: 5.2,
    battingAverage: 41,
    battingStrikeRate: 87,
    highestBowlingSpeed: "112 km/h"
},
 
{
    id: 106,
    name: "Joe Root",
    type: "Top Order Batter",
    othertype: "Middle Order Batter",
    handtype: "Right Hand Batter / Right Arm Off Spin",
    country: "england",
    matches: 171,
    totalRuns: 6522,
    highestScore: 133,
    catches: 85,
    fours: 580,
    sixes: 40,
    fifties: 39,
    hundreds: 16,
    wickets: 27,
    economy: 5.5,
    battingAverage: 49,
    battingStrikeRate: 87,
    highestBowlingSpeed: "112 km/h"
},
 
{
    id: 107,
    name: "Nathan Astle",
    type: "Opening Batter",
    othertype: "Bowling All-Rounder",
    handtype: "Right Hand Batter / Right Arm Medium",
    country: "newzealand",
    matches: 223,
    totalRuns: 7090,
    highestScore: 145,
    catches: 83,
    fours: 700,
    sixes: 80,
    fifties: 41,
    hundreds: 16,
    wickets: 99,
    economy: 4.9,
    battingAverage: 35,
    battingStrikeRate: 73,
    highestBowlingSpeed: "122 km/h"
},
 
{
    id: 108,
    name: "Tim Southee",
    type: "Fast Bowler",
    othertype: "Lower Order Batter",
    handtype: "Right Hand Batter / Right Arm Fast Medium",
    country: "newzealand",
    matches: 161,
    totalRuns: 720,
    highestScore: 55,
    catches: 60,
    fours: 60,
    sixes: 30,
    fifties: 1,
    hundreds: 0,
    wickets: 221,
    economy: 5.4,
    battingAverage: 11,
    battingStrikeRate: 110,
    highestBowlingSpeed: "140 km/h"
},
 
{
    id: 109,
    name: "Habibul Bashar",
    type: "Middle Order Batter",
    othertype: "captain",
    handtype: "Right Hand Batter",
    country: "bangladesh",
    matches: 111,
    totalRuns: 2168,
    highestScore: 78,
    catches: 30,
    fours: 230,
    sixes: 8,
    fifties: 14,
    hundreds: 0,
    wickets: 0,
    economy: 0,
    battingAverage: 21,
    battingStrikeRate: 68,
    highestBowlingSpeed: "0 km/h"
},
 
{
    id: 110,
    name: "David Warner",
    type: "Opening Batter",
    othertype: "Top Order Batter",
    handtype: "Left Hand Batter",
    country: "australia",
    matches: 161,
    totalRuns: 6932,
    highestScore: 179,
    catches: 75,
    fours: 700,
    sixes: 135,
    fifties: 33,
    hundreds: 22,
    wickets: 0,
    economy: 0,
    battingAverage: 45,
    battingStrikeRate: 97,
    highestBowlingSpeed: "0 km/h"
},
 
{
    id: 111,
    name: "Steve Smith",
    type: "Top Order Batter",
    othertype: "captain",
    handtype: "Right Hand Batter / Right Arm Leg Spin",
    country: "australia",
    matches: 155,
    totalRuns: 5800,
    highestScore: 164,
    catches: 90,
    fours: 480,
    sixes: 55,
    fifties: 32,
    hundreds: 12,
    wickets: 28,
    economy: 5.9,
    battingAverage: 43,
    battingStrikeRate: 88,
    highestBowlingSpeed: "118 km/h"
},
 
{
    id: 112,
    name: "Shakib Al Hasan",
    type: "Batting All-Rounder",
    othertype: "captain",
    handtype: "Left Hand Batter / Slow Left Arm",
    country: "bangladesh",
    matches: 247,
    totalRuns: 7570,
    highestScore: 134,
    catches: 60,
    fours: 700,
    sixes: 50,
    fifties: 56,
    hundreds: 9,
    wickets: 317,
    economy: 4.6,
    battingAverage: 37,
    battingStrikeRate: 82,
    highestBowlingSpeed: "92 km/h"
},
 
{
    id: 113,
    name: "Abdur Razzak",
    type: "Left Arm Spinner",
    othertype: "Lower Order Batter",
    handtype: "Left Hand Batter / Slow Left Arm",
    country: "bangladesh",
    matches: 153,
    totalRuns: 690,
    highestScore: 33,
    catches: 35,
    fours: 50,
    sixes: 10,
    fifties: 0,
    hundreds: 0,
    wickets: 207,
    economy: 4.6,
    battingAverage: 10,
    battingStrikeRate: 70,
    highestBowlingSpeed: "88 km/h"
},
 
{
    id: 114,
    name: "Jos Buttler",
    type: "Wicket-Keeper Batter",
    othertype: "captain",
    handtype: "Right Hand Batter",
    country: "england",
    matches: 181,
    totalRuns: 5236,
    highestScore: 162,
    catches: 240,
    fours: 420,
    sixes: 180,
    fifties: 27,
    hundreds: 11,
    wickets: 0,
    economy: 0,
    battingAverage: 41,
    battingStrikeRate: 118,
    highestBowlingSpeed: "0 km/h"
},
 
{
    id: 115,
    name: "Trent Boult",
    type: "Fast Bowler",
    othertype: "Tailender",
    handtype: "Right Hand Batter / Left Arm Fast",
    country: "newzealand",
    matches: 114,
    totalRuns: 250,
    highestScore: 21,
    catches: 45,
    fours: 18,
    sixes: 4,
    fifties: 0,
    hundreds: 0,
    wickets: 211,
    economy: 5,
    battingAverage: 7,
    battingStrikeRate: 70,
    highestBowlingSpeed: "145 km/h"
},
 
{
    id: 116,
    name: "Tamim Iqbal",
    type: "Opening Batter",
    othertype: "captain",
    handtype: "Left Hand Batter",
    country: "bangladesh",
    matches: 243,
    totalRuns: 8357,
    highestScore: 158,
    catches: 65,
    fours: 880,
    sixes: 100,
    fifties: 56,
    hundreds: 14,
    wickets: 0,
    economy: 0,
    battingAverage: 36,
    battingStrikeRate: 78,
    highestBowlingSpeed: "0 km/h"
},
 
{
    id: 117,
    name: "Ben Stokes",
    type: "Batting All-Rounder",
    othertype: "Middle Order Batter",
    handtype: "Left Hand Batter / Right Arm Fast Medium",
    country: "england",
    matches: 114,
    totalRuns: 3463,
    highestScore: 182,
    catches: 60,
    fours: 280,
    sixes: 90,
    fifties: 22,
    hundreds: 4,
    wickets: 74,
    economy: 6,
    battingAverage: 39,
    battingStrikeRate: 95,
    highestBowlingSpeed: "140 km/h"
},
 
{
    id: 118,
    name: "Liton Das",
    type: "Wicket-Keeper Batter",
    othertype: "Opening Batter",
    handtype: "Right Hand Batter",
    country: "bangladesh",
    matches: 100,
    totalRuns: 3200,
    highestScore: 176,
    catches: 110,
    fours: 360,
    sixes: 45,
    fifties: 18,
    hundreds: 6,
    wickets: 0,
    economy: 0,
    battingAverage: 35,
    battingStrikeRate: 88,
    highestBowlingSpeed: "0 km/h"
},
 
{
    id: 119,
    name: "Michael Clarke",
    type: "Middle Order Batter",
    othertype: "captain",
    handtype: "Right Hand Batter / Slow Left Arm",
    country: "australia",
    matches: 245,
    totalRuns: 7981,
    highestScore: 130,
    catches: 105,
    fours: 660,
    sixes: 55,
    fifties: 58,
    hundreds: 8,
    wickets: 57,
    economy: 5,
    battingAverage: 44,
    battingStrikeRate: 78,
    highestBowlingSpeed: "115 km/h"
},
 
{
    id: 120,
    name: "Malcolm Marshall",
    type: "Fast Bowler",
    othertype: "Lower Order Batter",
    handtype: "Right Hand Batter / Right Arm Fast",
    country: "westindies",
    matches: 136,
    totalRuns: 955,
    highestScore: 66,
    catches: 15,
    fours: 70,
    sixes: 8,
    fifties: 1,
    hundreds: 0,
    wickets: 157,
    economy: 3.5,
    battingAverage: 14,
    battingStrikeRate: 76,
    highestBowlingSpeed: "150 km/h"
},
 
{
    id: 121,
    name: "Jonty Rhodes",
    type: "Middle Order Batter",
    othertype: "Finisher",
    handtype: "Right Hand Batter",
    country: "southafrica",
    matches: 245,
    totalRuns: 5935,
    highestScore: 121,
    catches: 105,
    fours: 480,
    sixes: 35,
    fifties: 33,
    hundreds: 2,
    wickets: 0,
    economy: 0,
    battingAverage: 35,
    battingStrikeRate: 81,
    highestBowlingSpeed: "0 km/h"
}
];
